### ISSUE TITLE
ontologies not parsing (version 5.1.10)

### ISSUE THREAD

**Issue by rwynne** [owlcs/owlapi#1082]
Hi!
Ontologies are not parsing today with owlapi-distribution 5.1.10. (Tried with both SNOMED and NCIT)
Has there been a dependency update or should I look into something else with my system? 

```
<dependency>
  <groupId>net.sourceforge.owlapi</groupId>
  <artifactId>owlapi-distribution</artifactId>
  <version>5.1.10</version>
</dependency>
```

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "parserFactory" is null
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:185)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1107)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1020)
```

**Comment by rwynne** [comment]
Yikes!

I had a checkout of the elk-reasoner project in the same workspace as my others.
It must had caused some confusion to my environment. After removing it all is back to normal.

Please close.
