### ISSUE TITLE
build errors in owlapi-distribution related to maven-bundle-plugin

### ISSUE THREAD

**Issue by phillipross** [owlcs/owlapi#1096]
stack trace:

```
[INFO] --- bundle:3.2.0:bundle (default-bundle) @ owlapi-distribution ---
java.lang.NullPointerException
	at aQute.bnd.header.OSGiHeader.quote(OSGiHeader.java:150)
	at aQute.bnd.header.Attrs.append(Attrs.java:416)
	at aQute.bnd.header.Attrs.append(Attrs.java:397)
	at aQute.bnd.header.Parameters.append(Parameters.java:175)
	at aQute.bnd.header.Parameters.toString(Parameters.java:164)
	at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:788)
	at aQute.bnd.osgi.Builder.build(Builder.java:105)
	at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle(BundlePlugin.java:972)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:470)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:387)
	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:378)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:260)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:172)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:100)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:821)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:270)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] An internal error occurred
java.lang.IllegalArgumentException: Null query
    at aQute.lib.filter.Filter.<init> (Filter.java:291)
    at aQute.lib.filter.Filter.<init> (Filter.java:295)
    at aQute.bnd.osgi.Verifier.verifyRequirements (Verifier.java:737)
    at aQute.bnd.osgi.Verifier.verify (Verifier.java:537)
    at aQute.bnd.osgi.Builder.doVerify (Builder.java:532)
    at aQute.bnd.osgi.Builder.build (Builder.java:140)
    at org.apache.felix.bundleplugin.BundlePlugin.buildOSGiBundle (BundlePlugin.java:972)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:470)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:387)
    at org.apache.felix.bundleplugin.BundlePlugin.execute (BundlePlugin.java:378)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:260)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:172)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:100)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:821)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:270)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
```

**Comment by phillipross** [comment]
build environment: MacOS Monterey v12.6.2 on Apple Silicon
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: /Users/admin/.sdkman/candidates/maven/current
Java version: 11.0.18, vendor: Azul Systems, Inc., runtime: /Users/admin/.sdkman/candidates/java/11.0.18-zulu/zulu-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.2", arch: "aarch64", family: "mac"
