### ISSUE TITLE
Silencing import errors does not seem to work for OBO files

### ISSUE THREAD

**Issue by reckart** [owlcs/owlapi#1123]
When loading an OBO file that contains an import (such as the `example1.obo` file from this project's test data), it fails with an exception if network access is not available. 

Using a `AutoIRIMapper` and/or `MissingImportHandlingStrategy.SILENT` (as suggested [here](https://stackoverflow.com/questions/48249813/prevent-owlontologymanager-to-go-online)) does not seem to work.

```
        var manager = OWLManager.createOWLOntologyManager();

        // Does not seem to work for imports in OBO files....
        var iriMappers = manager.getIRIMappers();
        iriMappers.add(
                new AutoIRIMapper(new File(kbRepositoriesRoot, "materializedOntologies"), true));
        manager.getOntologyLoaderConfiguration()
                .setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);
        manager.getOntologyConfigurator()
                .setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);

        var ontology = manager.loadOntologyFromOntologyDocument(... input stream for OBO file ...);
```

**Comment by ignazio1977** [comment]
`OWLOntologyLoaderConfiguration` is an immutable object. When you set a property on it, you need to tell the manager to use the new object:

    manager.setOntologyLoaderConfiguration(
        manager.getOntologyConfigurator()
                .setMissingImportHandlingStrategy(
                     MissingImportHandlingStrategy.SILENT));

**Comment by reckart** [comment]
Thanks - doesn't help though unfortunately:

```
        var iriMappers = manager.getIRIMappers();
        iriMappers.add(
                new AutoIRIMapper(new File(kbRepositoriesRoot, "materializedOntologies"), true));
        manager.setOntologyLoaderConfiguration(manager.getOntologyLoaderConfiguration()
                .setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT));
        manager.setOntologyConfigurator(manager.getOntologyConfigurator()
                .setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT));
```

Stack trace:

```
Caused by: org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/po/imports/ncbitaxon_import.owl> Cause: OWLOntologyCreationIOException: java.net.SocketException: Bad file descriptor
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1710)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.tr(OWLAPIObo2Owl.java:505)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.convert(OWLAPIObo2Owl.java:445)
	at org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:47)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:195)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1105)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1055)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1005)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1025)
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.transduceOboToOwlFunctionalSyntax(KnowledgeBaseServiceImpl.java:690)
	at de.tudarmstadt.ukp.inception.kb.KnowledgeBaseServiceImpl.importData(KnowledgeBaseServiceImpl.java:650)
	... 5 more
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: OWLOntologyCreationIOException: java.net.SocketException: Bad file descriptor
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:216)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1105)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1055)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:955)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1663)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1703)
	... 15 more
Caused by: org.semanticweb.owlapi.io.OWLOntologyInputSourceException: java.net.SocketException: Bad file descriptor
	at org.semanticweb.owlapi.io.DocumentSources.getInputStream(DocumentSources.java:218)
	at org.semanticweb.owlapi.io.DocumentSources.wrapInput(DocumentSources.java:143)
	at org.semanticweb.owlapi.io.DocumentSources.wrapInputAsReader(DocumentSources.java:88)
	at org.semanticweb.owlapi.io.DocumentSources.wrapInputAsReader(DocumentSources.java:105)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:38)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:49)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:195)
	... 20 more
Caused by: java.net.SocketException: Bad file descriptor
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:325)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:976)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:824)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:783)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1691)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at org.semanticweb.owlapi.io.DocumentSources.connect(DocumentSources.java:229)
	at org.semanticweb.owlapi.io.DocumentSources.getInputStream(DocumentSources.java:209)
	... 26 more
```

**Comment by reckart** [comment]
I believe the OBO code is neither considering the IRI mapper nor the silence mode.

**Comment by ignazio1977** [comment]
which OWLAPI version are you using?

**Comment by reckart** [comment]
5.5.0

**Comment by reckart** [comment]
When I walked through the stack trace in the code, I had the impression that the OBO import code should catch Exception, wrap it in an `UnloadableImportException` and throw that. But I'm not sure even that would be enough. Probably the OBO code would actually need to consider the silencing flag itself.

**Comment by matthewhorridge** [comment]
Following up on this because I have the same problem.  The OBO parser ignores any specified loader configuration when it makes an import load request.  

The offending line is [here](https://github.com/owlcs/owlapi/blob/0e7166f4df44d40dbe66d74c3e8710ef4fd5ee4b/oboformat/src/main/java/org/obolibrary/obo2owl/OWLAPIObo2Owl.java#L507). 

In the above code you can see that the OBO parser creates a fresh (default) OWLOntologyLoaderConfiguration and ignores any configuration that's currently being used to load the currently OBO ontology.

@gouttegd do you know why the parser does this?  Is it intended?

Here is a (not exactly nice) work around:

```java
       OWLOntologyManager man = new OWLOntologyManagerImpl(new OWLDataFactoryImpl(), new NoOpReadWriteLock()) {
            @Override
            public void makeLoadImportRequest(OWLImportsDeclaration declaration, OWLOntologyLoaderConfiguration configuration) {
                var config = getOntologyLoaderConfiguration();
                super.makeLoadImportRequest(declaration, config);
            }
        };
        man.getOntologyFactories().add(new OWLOntologyFactoryImpl(new NonConcurrentOWLOntologyBuilder()));
        // Add parsers that we care about
        PriorityCollection<OWLParserFactory> ontologyParsers = man.getOntologyParsers();
        ontologyParsers.add(new OBOFormatOWLAPIParserFactory());
        ontologyParsers.add(new RDFXMLParserFactory());
        ontologyParsers.add(new OWLXMLParserFactory());
        ontologyParsers.add(new TurtleOntologyParserFactory());

        // Set the config we actually want for import loading
        var config = new OWLOntologyLoaderConfiguration()
                .setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);
        man.setOntologyLoaderConfiguration(config);
```
In the above, I create my own OWLOntologyManager from OWLOntologyManagerImpl that overrides the makeLoadImportRequest to force the config we actually want.

**Comment by gouttegd** [comment]
> do you know why the parser does this? Is it intended?

No idea. This code dates from long before I had even heard about the OWLAPI.

**Comment by ignazio1977** [comment]
The code creates a fresh configuration object while it should use the one coming from the manager at hand (so calling code can make the changes it wishes to make)

As to why - the code has been like that since it was written, ten years ago. Probably made sense at the time, I guess...

**Comment by ignazio1977** [comment]
As for the fix, assuming the `manager` member at line 507 is the same manager the calling code is using to manage the ontology, and so it has the correct config, changing

>            manager.makeLoadImportRequest(owlImportsDeclaration,
>                new OWLOntologyLoaderConfiguration());

to 

>            manager.makeLoadImportRequest(owlImportsDeclaration);

will do. I'll see if I can stick a test in there.

**Comment by matthewhorridge** [comment]
Thank you @ignazio1977! 😃
