### ISSUE TITLE
set up Owl API in eclipse

### ISSUE THREAD

**Issue by kumarravi123** [owlcs/owlapi#413]
Please somebody help to set up OWL API in eclipse. I have downloaded owlapi-osgidistribution-4.0.2 and set this into buildpath of eclipse. I try to run following code:

    import java.io.File;
    import com.github.jsonldjava.core.RDFDataset.IRI;
    public class test {
    public static void main(String[] args) throws OWLOntologyCreationException {
        File file = new File(
                "file:///g:/pizz.owl");
        OWLOntologyManager m = OWLManager.createOWLOntologyManager();
        OWLDataFactory f = OWLManager.getOWLDataFactory();
        OWLOntology o;
        o = m.loadOntologyFromOntologyDocument(file);
        OWLClass clsA = f.getOWLClass(IRI.create("urn:test#ClassA"));
        OWLClass clsB = f.getOWLClass(IRI.create("urn:test#ClassB"));
        OWLAxiom ax1 = f.getOWLSubClassOfAxiom(clsA, clsB);
        AddAxiom addAxiom1 = new AddAxiom(o, ax1);
        m.applyChange(addAxiom1);
        for (OWLClass cls : o.getClassesInSignature()) {
            System.out.println(cls.getIRI());
        }
        m.removeOntology(o);
    }
    }

I am getting following error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/inject/Provider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at test.main(test.java:18)
Caused by: java.lang.ClassNotFoundException: com.google.inject.Provider
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more

**Comment by ignazio1977** [comment]
You need to add all the transitive dependencies for owlapi. If you're not using maven, you need to add all the libraries listed in the pom file for 4.0.2

A shortcut for this is to unzip the 4.0.2-osgidistribution jar and add all the jars in the /lib folder to your classpath.

**Comment by SanjuTiwari** [comment]
IRI physicalURI = IRI.create(new File(ontosem.class.getClassLoader().getResource("/c:/travel.owl").getPath()));
giving nullPointer exception

**Comment by ignazio1977** [comment]
Accessing resources on the classpath requires package names, not file paths. Use a FileInputStream instead.

**Comment by SanjuTiwari** [comment]
I have made changes in this code and take File type object.
File file = new File("file:///c:/travel.owl");
    OWLOntology ontology = manager.loadOntologyFromOntologyDocument(file);
     
    System.out.println("Ontology : " + ontology.getOntologyID()); 
    System.out.println("Format      : " + manager.getOntologyFormat(ontology)); 
    
		System.out.println("Loaded ontology: " + ontology);
   fenetre = new OntoTree(ontology, "");
      fenetre.setVisible(true);

but still gives error:
org.semanticweb.owlapi.io.OWLOntologyInputSourceException: java.io.FileNotFoundException: file:\c:\travel.owl (The filename, directory name, or volume label syntax is incorrect)
cccccc	at org.semanticweb.owlapi.io.FileDocumentSource.getInputStream(FileDocumentSource.java:70)
	at org.semanticweb.owlapi.io.FileDocumentSource.getReader(FileDocumentSource.java:81)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:113)
	at org.coode.owlapi.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:89)
	at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:165)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:619)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:585)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:589)
	at project.OntoTree.main(OntoTree.java:161)
Caused by: java.io.FileNotFoundException: file:\c:\travel.owl (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.semanticweb.owlapi.io.FileDocumentSource.getInputStream(FileDocumentSource.java:67)
	... 8 more

**Comment by SanjuTiwari** [comment]
please help me to solve it.

**Comment by ignazio1977** [comment]
You're confusing protocols. When creating a File object, do not use file:///. When creating an IRI for a file, it is necessary to use file:///.

**Comment by ignazio1977** [comment]
getClassLoader().getResource() does NOT work with absolute file paths. You do not need it here, leave it out.

**Comment by SanjuTiwari** [comment]
Sorry but I am new for this and unable to get solution. I have studied
various codes on github so I am confused.
