### ISSUE TITLE
Issues with the latest 4.1.0 Release

### ISSUE THREAD

**Issue by martinjoconnor** [owlcs/owlapi#447]
I am having a variety of (related?) issues with the latest 4.1.0 and the [SWRLAPI]( https://github.com/protegeproject/swrlapi). Everything worked fine up to and including 4.1.0-RC2 (RC3 and RC4 are not on Maven Central so I did not try with those.) 

I do not have time at the moment to track these down in more detail but I thought I'd open an issue to see if there is some obvious configuration problem in my project.

Everything compiles successfully but I get the following error when I run the integration tests in the project: 

<pre>Oct 29, 2015 4:54:46 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.NoClassDefFoundError: org/openrdf/rio/RDFFormat
org.semanticweb.owlapi.model.OWLRuntimeException: Injection failed for factory: interface org.semanticweb.owlapi.model.OWLDocumentFormatFactory type: interface org.semanticweb.owlapi.model.OWLDocumentFormat
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadFactories(OWLAPIServiceLoaderModule.java:114)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(OWLAPIServiceLoaderModule.java:58)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:89)
	at org.semanticweb.owlapi.apibinding.OWLManager.getOWLDataFactory(OWLManager.java:78)
	at org.semanticweb.owlapi.apibinding.OWLFunctionalSyntaxFactory.<clinit>(OWLFunctionalSyntaxFactory.java:133)
	at org.swrlapi.test.IntegrationTestBase.<clinit>(IntegrationTestBase.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:202)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:251)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:248)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
Caused by: java.util.ServiceConfigurationError: org.semanticweb.owlapi.model.OWLDocumentFormatFactory: Provider org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.google.common.collect.Iterators.addAll(Iterators.java:362)
	at com.google.common.collect.Iterables.addAll(Iterables.java:354)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.load(OWLAPIServiceLoaderModule.java:98)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadFactories(OWLAPIServiceLoaderModule.java:109)
	... 33 more
Caused by: java.lang.NoClassDefFoundError: org/openrdf/rio/RDFFormat
	at org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory.<init>(BinaryRDFDocumentFormatFactory.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 39 more

java.lang.ExceptionInInitializerError
	at org.swrlapi.test.IntegrationTestBase.<clinit>(IntegrationTestBase.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:202)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:251)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:248)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.util.Set<org.semanticweb.owlapi.io.OWLParserFactory> was bound.
  while locating java.util.Set<org.semanticweb.owlapi.io.OWLParserFactory>
    for parameter 0 at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyParsers(OWLOntologyManagerImpl.java:1348)
  at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyParsers(OWLOntologyManagerImpl.java:1348)
  at uk.ac.manchester.cs.owl.owlapi.OWLAPIImplModule.configure(OWLAPIImplModule.java:61)

2) No implementation for java.util.Set<org.semanticweb.owlapi.model.OWLStorerFactory> was bound.
  while locating java.util.Set<org.semanticweb.owlapi.model.OWLStorerFactory>
    for parameter 0 at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyStorers(OWLOntologyManagerImpl.java:1286)
  at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyStorers(OWLOntologyManagerImpl.java:1286)
  at uk.ac.manchester.cs.owl.owlapi.OWLAPIImplModule.configure(OWLAPIImplModule.java:61)

3) An exception was caught and reported. Message: Injection failed for factory: interface org.semanticweb.owlapi.model.OWLDocumentFormatFactory type: interface org.semanticweb.owlapi.model.OWLDocumentFormat
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

3 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:89)
	at org.semanticweb.owlapi.apibinding.OWLManager.getOWLDataFactory(OWLManager.java:78)
	at org.semanticweb.owlapi.apibinding.OWLFunctionalSyntaxFactory.<clinit>(OWLFunctionalSyntaxFactory.java:133)
	... 21 more
Caused by: org.semanticweb.owlapi.model.OWLRuntimeException: Injection failed for factory: interface org.semanticweb.owlapi.model.OWLDocumentFormatFactory type: interface org.semanticweb.owlapi.model.OWLDocumentFormat
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadFactories(OWLAPIServiceLoaderModule.java:114)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(OWLAPIServiceLoaderModule.java:58)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 27 more
Caused by: java.util.ServiceConfigurationError: org.semanticweb.owlapi.model.OWLDocumentFormatFactory: Provider org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.google.common.collect.Iterators.addAll(Iterators.java:362)
	at com.google.common.collect.Iterables.addAll(Iterables.java:354)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.load(OWLAPIServiceLoaderModule.java:98)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadFactories(OWLAPIServiceLoaderModule.java:109)
	... 33 more
Caused by: java.lang.NoClassDefFoundError: org/openrdf/rio/RDFFormat
	at org.semanticweb.owlapi.formats.BinaryRDFDocumentFormatFactory.<init>(BinaryRDFDocumentFormatFactory.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 39 more
</pre>

The project has a fairly small set of standard external dependencies.

<pre>
&lt;java.version&gt;1.8&lt;/java.version&gt; 
&lt;owlapi.version&gt;4.1.0&lt;/owlapi.version&gt; 
&lt;jep.version&gt;2.4.0&lt;/jep.version&gt;
&lt;axis.osgi.version&gt;1.4_1&lt;/axis.osgi.version&gt;
&lt;commons.discovery.osgi.version&gt;0.4_1&lt;/commons.discovery.osgi.version&gt;
&lt;checker.framework.version&gt;1.7.5&lt;/checker.framework.version&gt;
&lt;junit.version&gt;4.11&lt;/junit.version&gt;
&lt;slf4j.version&gt;1.6.1&lt;/slf4j.version&gt;
...
&lt;dependency&gt;
  &lt;groupId&gt;net.sourceforge.owlapi&lt;/groupId&gt;
  &lt;artifactId&gt;owlapi-osgidistribution&lt;/artifactId&gt;
  &lt;version&gt;${owlapi.version}&lt;/version&gt;
&lt;/dependency&gt;

</pre>

Thanks.
Martin

**Comment by martinjoconnor** [comment]
Here is a simple example that will generate the error at runtime:

<pre>
package org.swrlapi.test;

import org.semanticweb.owlapi.model.OWLDatatype;
import org.semanticweb.owlapi.vocab.Namespaces;
import static org.semanticweb.owlapi.apibinding.OWLFunctionalSyntaxFactory.Datatype;
import static org.semanticweb.owlapi.apibinding.OWLFunctionalSyntaxFactory.IRI;
public class Fred
{
  private static final OWLDatatype RDFS_LITERAL = Datatype(IRI(Namespaces.RDFS + "Literal"));
  public static void main(String[] args) {}
}
<pre>

**Comment by martinjoconnor** [comment]
I did some digging via Git. The last OWLAPI version that worked with the SWRLAPI is bc572e3, which is late in the 4.1.0-RC2 cycle. The next commit (506e735) does not compile. The commit after that (a6f82d0; which is, oddly, versioned 4.1.0-SNAPSHOT and is no longer versioned 4.1.0-RC2) gives the error indicated above. 

There do not appear to be any code changes between bc572e3 and a6f82d0, but there is quite a bit of POM activity. Sone of this activity relates to Sesame RIO - which appears to be involved in the reported exception.

**Comment by ignazio1977** [comment]
Apologies, I've not had a chance to investigate yet.

We had a problem in 4.0.2 where not all necessary dependencies were included in the distribution pom - this sounds related. I'm surprised by the Set error though, not seen that before.

I'll try to replicate later today.

**Comment by ignazio1977** [comment]
I've checked out SWRLAPI and tried to compile and run tests with owlapi-distribution instead of owlapi-osgidistribution. The tests ran fine in that case.

So, what I think is happening is that the poms for the two distributions are coming out slightly different - while the main difference should be only that the osgi one has embedded dependencies and exports them to an OSGi container.

My guess is that, once compiled with owlapi-distribution, you can run the plugin in Protege - I've tried the latest Protege with 4.1.0 osgidistribution and it works, so we should be fine on that front.

This should allow you to continue working while I sort out the osgidistribution pom - I'll make a 4.1.1 release once that's done.

Thanks for the report, it's been very useful.

**Comment by ignazio1977** [comment]
I've fixed this and released 4.1.1

**Comment by martinjoconnor** [comment]
Fixed. Thanks!
