### ISSUE TITLE
Null pointer exception when using pellet reasoner

### ISSUE THREAD

**Issue by RimHelaoui** [owlcs/owlapi#474]
Hello,

I am getting a null pointer exception when trying to use any of the pellet reasoner methods (I tried to retrieve equivalent classes, superclasses..). I do not understand what the reason is ( the ontology is consistent and not empty). I would very much appreciate  any hint!

Here is the detailed error msg:

java.lang.NullPointerException
	at javax.xml.bind.DatatypeConverter.parseInteger(DatatypeConverter.java:134)
	at com.clarkparsia.pellet.datatypes.types.real.XSDInteger.fromLexicalForm(XSDInteger.java:45)
	at com.clarkparsia.pellet.datatypes.types.real.AbstractDerivedIntegerType.getCanonicalRepresentation(AbstractDerivedIntegerType.java:72)
	at com.clarkparsia.pellet.datatypes.DatatypeReasonerImpl.getCanonicalRepresentation(DatatypeReasonerImpl.java:365)
	at org.mindswap.pellet.tableau.completion.rule.SomeValuesRule.applySomeValuesRule(SomeValuesRule.java:159)
	at org.mindswap.pellet.tableau.completion.rule.SomeValuesRule.apply(SomeValuesRule.java:64)
	at org.mindswap.pellet.tableau.completion.EmptySRIQStrategy.expand(EmptySRIQStrategy.java:303)
	at org.mindswap.pellet.tableau.completion.EmptySRIQStrategy.complete(EmptySRIQStrategy.java:162)
	at org.mindswap.pellet.ABox.isConsistent(ABox.java:1423)
	at org.mindswap.pellet.ABox.isSatisfiable(ABox.java:595)
	at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.checkSatisfiability(CDOptimizedTaxonomyBuilder.java:763)
	at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:814)
	at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:265)
	at org.mindswap.pellet.taxonomy.CDOptimizedTaxonomyBuilder.classify(CDOptimizedTaxonomyBuilder.java:218)
	at org.mindswap.pellet.KnowledgeBase.classify(KnowledgeBase.java:2095)
	at org.mindswap.pellet.KnowledgeBase.getSuperClasses(KnowledgeBase.java:3169)
	at com.clarkparsia.pellet.owlapiv3.PelletReasoner.getSuperClasses(PelletReasoner.java:759)

**Comment by ignazio1977** [comment]
This is either a bug or a problem in the data. Can you share the ontology?

**Comment by RimHelaoui** [comment]
Thank you very much for the answer.
Sure I can (see attachement).

Looking forward to your suggestions!

Cheers,

On Tue, Dec 22, 2015 at 4:31 PM, Ignazio Palmisano <notifications@github.com

**Comment by ignazio1977** [comment]
The attachment didn't make it through to the GitHub issue, can you email it to me directly at ipalmisano.mailings@gmail.com ?

**Comment by ignazio1977** [comment]
I've tried to replicate this issue and failed. Which version of Pellet and OWLAPI are you using?

I've tried OWLAPI 4 and Pellet 2.4.0-ignazio1977 (the version submitted to ORE 2015) and it appears to work fine:

    @Test
    public void should() throws OWLOntologyCreationException {
        OWLOntology o = OWLManager.createOWLOntologyManager().loadOntologyFromOntologyDocument(new File(
            "ElogSimpleActivityOntology.owl"));
        System.out.println("CheckParsing.should() " + Profiles.OWL2_DL.checkOntology(o));
        OWLReasoner r = new PelletReasonerFactory().createReasoner(o);
        System.out.println("CheckParsing.should() " + r.isConsistent());
        for (OWLClass c : o.getClassesInSignature()) {
            System.out.println("CheckParsing.should() " + r.getEquivalentClasses(c));
        }
    }

My fork, with all the required libraries, is available on Maven Central and here: https://github.com/ignazio1977/ore2015submission
