### ISSUE TITLE
XML literal is not self contained

### ISSUE THREAD

**Issue by rwynne** [owlcs/owlapi#509]
Hi,

This may be related to https://github.com/owlcs/owlapi/issues/495.

I'm testing 4.2.3 with a roundtrip (load and save) of our NCI Thesaurus raw export.  It reads the raw file fine.  During save, however, the writing stops before a class containing an ampersand in its FULL_SYN (XML Literal annotation).  The exceptions are below, and here is the offending class snippet on the way in:

`  <owl:Class rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A_and_D_Ointment">
    <rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Topical_Preparation"/>
    <code rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >C28794</code>
    <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >A and D Ointment</rdfs:label>
    <FULL_SYN rdf:parseType="Literal"><ncicp:ComplexTerm xmlns:ncicp="http://ncicb.nci.nih.gov/xml/owl/EVS/ComplexProperties.xsd#"><ncicp:term-name>A&amp;D Ointment</ncicp:term-name><ncicp:term-group>SY</ncicp:term-group><ncicp:term-source>NCI</ncicp:term-source></ncicp:ComplexTerm></FULL_SYN>
</owl:Class>
`

` 
org.semanticweb.owlapi.model.OWLOntologyStorageException: java.io.IOException: XML literal is not self contained: "<ncicp:ComplexTerm xmlns:ncicp="http://ncicb.nci.nih.gov/xml/owl/EVS/ComplexProperties.xsd#"><ncicp:term-name>A&D Ointment</ncicp:term-name><ncicp:term-group>SY</ncicp:term-group><ncicp:term-source>NCI</ncicp:term-source></ncicp:ComplexTerm>"
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLStorer.storeOntology(RDFXMLStorer.java:61)
       at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:99)
       at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:64)
       at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1264)
       at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1249)
       at gov.nih.nci.evs.owl.data.SaveTest.run(SaveTest.java:42)
       at gov.nih.nci.evs.owl.data.SaveTest.main(SaveTest.java:35)
Caused by: java.io.IOException: XML literal is not self contained: "<ncicp:ComplexTerm xmlns:ncicp="http://ncicb.nci.nih.gov/xml/owl/EVS/ComplexProperties.xsd#"><ncicp:term-name>A&D Ointment</ncicp:term-name><ncicp:term-group>SY</ncicp:term-group><ncicp:term-source>NCI</ncicp:term-source></ncicp:ComplexTerm>"
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.checkProperXMLLiteral(XMLWriterImpl.java:446)
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeTextContent(XMLWriterImpl.java:428)
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeElementStart(XMLWriterImpl.java:339)
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.writeElementEnd(XMLWriterImpl.java:384)
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl.writeEndElement(XMLWriterImpl.java:165)
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLWriter.writeEndElement(RDFXMLWriter.java:116)
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLRenderer.render(RDFXMLRenderer.java:247)
       at org.semanticweb.owlapi.rdf.RDFRendererBase.renderEntity(RDFRendererBase.java:265)
       at org.semanticweb.owlapi.rdf.RDFRendererBase.renderEntities(RDFRendererBase.java:257)
       at org.semanticweb.owlapi.rdf.RDFRendererBase.renderInOntologySignatureEntities(RDFRendererBase.java:226)
       at org.semanticweb.owlapi.rdf.RDFRendererBase.renderOntologyComponents(RDFRendererBase.java:208)
       at org.semanticweb.owlapi.rdf.RDFRendererBase.render(RDFRendererBase.java:203)
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLStorer.storeOntology(RDFXMLStorer.java:59)
       ... 6 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 114; The reference to entity "D" must end with the ';' delimiter.
       at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
       at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
       at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
       at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
       at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(XMLDocumentFragmentScannerImpl.java:1850)
       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3067)
       at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
       at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
       at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
       at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
       at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
       at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
       at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
       at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
       at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
       at org.semanticweb.owlapi.rdf.rdfxml.renderer.XMLWriterImpl$XMLElement.checkProperXMLLiteral(XMLWriterImpl.java:443)
       ... 18 more
`

**Comment by ignazio1977** [comment]
The problem here is that the XML in the literal is not valid:

`org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 114; The reference to entity "D" must end with the ';' delimiter.`

The ampersand needs to be `&amp;` if it is to be used in that position.

What does the input in the original input file look like?

**Comment by rwynne** [comment]
I don't see anything wrong with it.  The ampersand is escaped as &amp; in the Literal.

`  <owl:Class rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#A_and_D_Ointment">
    <rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Topical_Preparation"/>
    <code rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >C28794</code>
    <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >A and D Ointment</rdfs:label>
    <FULL_SYN rdf:parseType="Literal"><ncicp:ComplexTerm xmlns:ncicp="http://ncicb.nci.nih.gov/xml/owl/EVS/ComplexProperties.xsd#"><ncicp:term-name>A and D Ointment</ncicp:term-name><ncicp:term-group>PT</ncicp:term-group><ncicp:term-source>NCI</ncicp:term-source></ncicp:ComplexTerm></FULL_SYN>
    <Legacy_Concept_Name rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >A_and_D_Ointment</Legacy_Concept_Name>
    <FULL_SYN rdf:parseType="Literal"><ncicp:ComplexTerm xmlns:ncicp="http://ncicb.nci.nih.gov/xml/owl/EVS/ComplexProperties.xsd#"><ncicp:term-name>A&amp;D Ointment</ncicp:term-name><ncicp:term-group>SY</ncicp:term-group><ncicp:term-source>NCI</ncicp:term-source></ncicp:ComplexTerm></FULL_SYN>
    <Preferred_Name rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >A and D Ointment</Preferred_Name>
    <Semantic_Type rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >Pharmacologic Substance</Semantic_Type>
    <UMLS_CUI rdf:datatype="http://www.w3.org/2001/XMLSchema#string"
    >C0305093</UMLS_CUI>
    <DEFINITION rdf:parseType="Literal"><ncicp:ComplexDefinition xmlns:ncicp="http://ncicb.nci.nih.gov/xml/owl/EVS/ComplexProperties.xsd#"><ncicp:def-definition>A topical preparation containing fat-soluble vitamins A and D usually in a lanolin-petrolatum base, A and D Ointment promotes healing of minor burns, rashes, sunburn, skin irritations, and acne; and prevents diaper rash. Vitamin A is essential for diverse cellular functions, immune system functions, and maintenance of mucous membranes, while vitamin D regulates calcium and phosphorous metabolism. (NCI04)</ncicp:def-definition><ncicp:def-source>NCI</ncicp:def-source><ncicp:Definition_Reviewer_Name>DEFAULT_Review</ncicp:Definition_Reviewer_Name><ncicp:Definition_Review_Date>060127</ncicp:Definition_Review_Date></ncicp:ComplexDefinition></DEFINITION>
  </owl:Class>`

**Comment by rwynne** [comment]
Wow, ok, still trying to get the hang of the github formatting here.  Apologies, the ampersand is escaped properly in the input as 
`&amp;`

**Comment by sesuncedu** [comment]
XMLWriterImpl explicitly doesn't escape XML literals.

Instead, the value is  checked to see if it can be parsed (throwing the
relevant exception).

I am not sure if the internal values of xml literals  should be kept
escaped, or the rendered form should do the escaping.

Line 424, XMLWriterImpl::writeTextContent

**Comment by ignazio1977** [comment]
The problem is probably in the literal itself, during parsing important data is being mangled.

**Comment by rwynne** [comment]
I'd imagine that if the bug is in the writer, then one solution may be to test whether or not the value should be wrapped in CDATA or even escaped (again?) on out.

**Comment by ignazio1977** [comment]
Can't be escaped or cdataed without breaking compliance with the specs. Much as I disagree with this particular piece of them, we can't do that.

I believe the issue here is the way the literal is parsed. There is no separation between surrounding XML and literal, so the sax handler has to rebuild the XML from what it reads, and I don't think it takes into account characters that need escaping when preparing the literal form to pass to the data factory.

**Comment by sesuncedu** [comment]
Tell me if this makes sense:

1. XML literals must be self contained, and thus cannot contain any entity
references other than character entities.

2. All character references are expanded during the parse process.

3. There are two apache sax features that can be set to enable notification
of character and built-in entity expansion.

4. These can be toggled when beginning an entity with parsetype Literal.

5. RDF / XML is the bestest.

**Comment by sesuncedu** [comment]
Ah...

http://stackoverflow.com/a/5524862/5552471

**Comment by ignazio1977** [comment]
2 and 5 are obviously true, and I'm only sarcastic once every three sentences.

**Comment by ignazio1977** [comment]
Good link. Yeah, if there was an easy way of just getting byte for byte the content of the XML literal, that would be awesome. I haven't found one yet.

**Comment by safrant** [comment]
If it is CDATA on the way in will that keep it from being mangled?

**Comment by sesuncedu** [comment]
> If it is CDATA on the way in will that keep it from being mangled?

That would have been a much better design for RDF/XML :-(
But it is what it is (and what should never be).

**Comment by ignazio1977** [comment]
Found the problem. By the time the (OWLAPI) parser sees the data, the entity has been resolved - so only `&` is seen. I've fixed this by escaping the new characters as they're seen.
