### ISSUE TITLE
Import IRI not resolved correctly in OBO input

### ISSUE THREAD

**Issue by tudorache** [owlcs/owlapi#523]
Reported on the Protege mailing list, but then checked with OWL API code, and could reproduce.

Steps:
- Load this file:
https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo 

- An import-not-found exception is thrown.

The import statement in the file is:
import: https://raw.githubusercontent.com/pato-ontology/pato/master/pato.obo

The OWL API tries to load the import after prefixing it with the local path:
file:/work/src/owlapi_test/https:/raw.githubusercontent.com/pato-ontology/pato/master/pato.obo

Exception below:
```
[Fatal Error] :1:1: Content is not allowed in prolog.
Exception in thread "main" org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <file:/work/src/owlapi_test/https:/raw.githubusercontent.com/pato-ontology/pato/master/pato.obo> Cause: /work/src/owlapi_test/https:/raw.githubusercontent.com/pato-ontology/pato/master/pato.obo (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1652)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.tr(OWLAPIObo2Owl.java:382)
	at org.obolibrary.obo2owl.OWLAPIObo2Owl.convert(OWLAPIObo2Owl.java:314)
	at org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:88)
	at org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:83)
	at org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser.parse(OBOFormatOWLAPIParser.java:58)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:891)
	at owlapitest.OWLAPI_Test.loadOBOTest(OWLAPI_Test.java:22)
	at owlapitest.OWLAPI_Test.main(OWLAPI_Test.java:15)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: /work/src/owlapi_test/https:/raw.githubusercontent.com/pato-ontology/pato/master/pato.obo (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:202)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:935)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1610)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1646)
	... 12 more
Caused by: java.io.FileNotFoundException: /work/src/owlapi_test/https:/raw.githubusercontent.com/pato-ontology/pato/master/pato.obo (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:165)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:127)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:232)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193)
	... 17 more
```

**Comment by ignazio1977** [comment]
Bad protocol detection https was not considered. Fixed now.
