### ISSUE TITLE
SubObjectProperties testing

### ISSUE THREAD

**Issue by Buglish** [owlcs/owlapi#532]
With OWL API v3 I am using the getSubObjectProperties function in the OWLReasoner class to extract objectProperties with the accompanying domain and range.
Example source code [here](https://github.com/owlcs/owlapi/blob/version3/contract/src/test/java/org/coode/owlapi/examples/Examples.java)
While running through the Hierarchy when testing if the parent class has the property it shows true for all the properties running through all the classes.

```
for (OWLObjectPropertyExpression prop : ontology.getObjectPropertiesInSignature()) {
            boolean sat = hasProperty(manager, reasoner, owlClass, prop);
            if (sat) {
                System.out.println("Instances of " + labelFor(owlClass) + " necessarily have the property " + prop);
           }
```

Secondly how does one get the subclass related to the correctly linked object property?

**Comment by LorenzBuehmann** [comment]
What is the problem with the current code? And what exactly does `hasProperty`? And what do you expect but does not happen?

Moreover, the expression "class has property" is not valid in OWL.  Given a property `p` and a  domain `A`, due to inference any instance `x` that is connected to a `y` by property `p`, i.e. `p(x, y)` belongs to `A` due to inference. Vice versa for range indeed.

**Comment by Buglish** [comment]
line 1445
https://github.com/phillord/owl-api/blob/master/contract/src/test/java/org/coode/owlapi/examples/Examples.java

**Comment by LorenzBuehmann** [comment]
Ok, you linked to a fork of OWL API, but I understand now what the method does.Without seeing the ontology it's hard to help as a reasoner is used and there might be some axioms that lead to the observed result. In addition, I'd suggest to check first if the same happens with OWL API 4 (although I think yes). Can you share the ontology?

**Comment by Buglish** [comment]
Due to the JDK I cannot move to OWL API 4
The email i had been processing is below.
http://www.indiana.edu/~awny/ontologies/scro.owl

**Comment by Buglish** [comment]
By using examples specific to this fork and version 3 I used the below link as a base but get a null point exception.
https://github.com/owlcs/owlapi/blob/version3/contract/src/test/java/uk/ac/manchester/owl/owlapi/tutorial/examples/SimpleHierarchyExample.java#L159

Ontology Loaded...
Document IRI: file:/C:/_exp/scro_org.owl
Ontology : OntologyID(OntologyIRI(<http://www.indiana.edu/~awny/ontologies/scro.owl>))
Format : RDF/XML
java.lang.NullPointerException

Is there a simpler way to extract all the class property and subclass properties in version 3?

**Comment by ignazio1977** [comment]
can you post the rest of the stack trace for the null pointer exception?

**Comment by Buglish** [comment]
```
java.lang.NullPointerException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:171)
        at org.ontoware.text2onto.ontology.OWL2Reader.read(OWL2Reader.java:160)
        at org.ontoware.text2onto.pom.POMFactory.newPOM(POMFactory.java:41)
        at org.ontoware.text2onto.gui.Text2Onto.doImport(Text2Onto.java:562)
        at org.ontoware.text2onto.gui.Text2Onto.access$400(Text2Onto.java:42)
        at org.ontoware.text2onto.gui.Text2Onto$6.actionPerformed(Text2Onto.java:363)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:357)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:809)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:850)
        at java.awt.Component.processMouseEvent(Component.java:6297)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
        at java.awt.Component.processEvent(Component.java:6062)
        at java.awt.Container.processEvent(Container.java:2039)
        at java.awt.Component.dispatchEventImpl(Component.java:4660)
        at java.awt.Container.dispatchEventImpl(Container.java:2097)
        at java.awt.Component.dispatchEvent(Component.java:4488)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4575)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4236)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4166)
        at java.awt.Container.dispatchEventImpl(Container.java:2083)
        at java.awt.Window.dispatchEventImpl(Window.java:2489)
        at java.awt.Component.dispatchEvent(Component.java:4488)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:674)
        at java.awt.EventQueue.access$400(EventQueue.java:81)
        at java.awt.EventQueue$2.run(EventQueue.java:633)
        at java.awt.EventQueue$2.run(EventQueue.java:631)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:647)
        at java.awt.EventQueue$3.run(EventQueue.java:645)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:644)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by ansell** [comment]
Not knowing what is on line 160 of OWL2Reader, it seems like you are missing an expected class on the classpath, and it probably isn't relevant here. You should take this up with the makers of the library behind org.ontoware.text2onto

**Comment by sesuncedu** [comment]
The problem may be due to passing a null string in as the reasoner factory
name.

**Comment by ignazio1977** [comment]
@Buglish the code you're using is correct, however the exception you're essing does not originate in OWLAPI code. I cannot find the OWL2Reader class anywhere - can you share the code here?

**Comment by Buglish** [comment]
Thanks.
I resolved the issue by not using the null string class.
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLReasonerFactory reasonerFactory = new StructuralReasonerFactory();
IRI documentIRI = IRI.create(physicalURIPath.toString());
OWLOntology ontology = manager.loadOntologyFromOntologyDocument(documentIRI);        
SimpleHierarchyExtract simpleHierarchy = new SimpleHierarchyExtract( reasonerFactory, ontology);
