### ISSUE TITLE
Runtime exception when creating OWLOntologyManager

### ISSUE THREAD

**Issue by krisnadhi** [owlcs/owlapi#579]
Hi,

I have the following (possibly a newbie) problem when creating OWLOntologyManager.

When creating an OWLOntologyManager (code below):

```
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.OWLOntologyManager;
public class SanityCheckerMain {
	public static void main(String[] args) {
		OWLOntologyManager m = OWLManager.createOWLOntologyManager();
	}
}

```
I got the following exception in runtime (the code compiles successfully):

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Sets
	at com.google.inject.internal.Errors.<clinit>(Errors.java:82)
	at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:62)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:82)
	at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:87)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:52)
	at SanityCheckerMain.main(SanityCheckerMain.java:8)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Sets
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```

Any idea or workaround?
IDE: Eclipse, Java 1.8
The project is a Maven project with the following pom:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>GeolinkDataSanityChecker</groupId>
  <artifactId>GeolinkDataSanityChecker</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
  	<dependency>
  		<groupId>net.sourceforge.owlapi</groupId>
  		<artifactId>owlapi-distribution</artifactId>
  		<version>5.0.4</version>
  	</dependency>
  </dependencies>
</project>

```

**Comment by ignazio1977** [comment]
The error you're getting seems to be due to lacking Guava in the classpath. The Maven setup appears correct (and since the code compiles, that's confirmation), but, as the error is at runtime, maybe your compile and runtime classpath differ.

Try updating the project (right click on project -> Maven -> Update project) to make sure the Eclipse .classpath file is up to date with the pom file.

**Comment by ansell** [comment]
Could you run "mvn dependency:tree" inside of your project and verify that Google Guava (which should have the import that you are missing) isn't one of the jars that are currently included?

**Comment by krisnadhi** [comment]
Hi,
Thanks for the suggestion. 

I tried @ignazio1977's suggestion, but the same error persists.
I have run mvn dependency:tree and I did find the following line: 
```com.google.guava:guava:jar:19.0:compile```
So, guava is there. 

I also looked at the classpath in Run Configurations, and Maven Dependencies are included in the classpath information there.

I have asked a colleague to run the program in his computer using the same Eclipse version and the same pom.xml, and it was able to run fine there. So, is there a hidden setting I'm missing?

**Comment by ignazio1977** [comment]
Possibly a corrupt library in your local maven repository? Try deleting the guava libraries from your maven folder and rebuild, this will download a fresh copy.

**Comment by ignazio1977** [comment]
My bad - the stack trace relates to Guice not Guava.

**Comment by anzalharris** [comment]
@krisnadhi Where you able to solve this issue? I am new to all of this and have the same issue. Would be a great help if can help me.

**Comment by ignazio1977** [comment]
@anzalharris hi, if you have the same issue please post your pom file contents and the error message you get. You can use this issue or open a new one.

**Comment by anzalharris** [comment]
@ignazio1977 my problem was due to the version number of the OWL API when I use 5.1.19 this problem was solved.

**Comment by iLykTurtlz** [comment]
I'm also a newbie with a similar problem, though I've been trying to get started for months now.  I think I'm close, but OWLManager doesn't work for me.  Is there a better way nowadays?

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/java.util.Optional.of(Optional.java:113)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:194)
	at java.base/java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:191)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at org.semanticweb.owlapi.utilities.Injector.getImplementation(Injector.java:246)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:119)
	at owlapi.tutorial.OWLAPIFirst.main(OWLAPIFirst.java:8)`

Here's my code and my pom:

`package owlapi.tutorial;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class OWLAPIFirst {
	public static void main(String[] args) {
		OWLOntologyManager man = OWLManager.createOWLOntologyManager();
		System.out.println(man.getOntologies().size());
		
	}
}
`

`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>owlapi.tutorial</groupId>
  <artifactId>msc</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
<dependency>
<groupId>junit</groupId>
<artifactId>junit</artifactId>
<version>3.8.1</version>
<scope>test</scope>
</dependency>
<dependency>
<groupId>net.sourceforge.owlapi</groupId>
<artifactId>owlapi-distribution</artifactId>
<version>5.5.0</version>
</dependency>
</dependencies>
</project>`

Any advice at all?  Thanks!
