### ISSUE TITLE
Unable to use owl api in android

### ISSUE THREAD

**Issue by paola2701** [owlcs/owlapi#652]
Hello everyone. I need to import owl api in Android, so I added the jar file to the 'libs' directory and checked the build.gradle file to make sure it included the dependencies properly.
Still, the project fails as soon as it comes to use the owl api classes and methods. 
Is there a way to use owl api in Android? Has it ever been tested? I didn't found anything on the internet about this. 

Thanks in advance.

**Comment by sesuncedu** [comment]
Which jar, which version of owlapi, and which version of Android, and which
compiler suite?

Old versions of the owlapi have run on Android, but it hadn't been a
targeted platform, and there is considerable use of Java 1.8 features that
are problematic for pre-Nougat releases. Default methods require support in
ART, so Nougat is probably the baseline.

Where does the project fail, and what does lint report?

Jeff Pan at Aberdeen has published some work on reasoning  on Android.

Improved Android compatibility and performance is a goal for the next major
OWLAPI release ; the main activity so far is a migration to gradle :)

**Comment by px91** [comment]
The jar file are owlapi-distribution-4.3.1 and owlapi-dependencypack-4.3.1 (this one extracted). 
I'm using Android Studio 2.3.1 and to run apps I use my device which has Android 6.0.
The project fails as soon as I try to instantiate the ontology manager, here:
 `OWLOntologyManager manager = OWLManager.createOWLOntologyManager();`
i.e. when I try to use methods of owlapi. The app interrupts itself with the message "The app stopped working". I don't see errors in the console. 

What do you suggest to do? I can't emulate a device since my processor is not Intel.
Which version of owlapi has been tested successfully on Android?  

Thank you

**Comment by px91** [comment]
Actually, the logcat reports this (i didn't notice it before): 
`04-12 13:27:43.899 1681-1681/com.example.acer.prova E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.example.acer.prova, PID: 1681
                                                                      java.lang.ExceptionInInitializerError
                                                                          at com.google.inject.internal.cglib.core.$MethodWrapper.create(MethodWrapper.java:0)
                                                                          at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:25)
                                                                          at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
                                                                          at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
                                                                          at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
                                                                          at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
                                                                          at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:231)
                                                                          at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
                                                                          at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:252)
                                                                          at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:203)
                                                                          at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:69)
                                                                          at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
                                                                          at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
                                                                          at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
                                                                          at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
                                                                          at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
                                                                          at com.google.inject.spi.Elements.getElements(Elements.java:110)
                                                                          at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
                                                                          at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
                                                                          at com.google.inject.Guice.createInjector(Guice.java:99)
                                                                          at com.google.inject.Guice.createInjector(Guice.java:73)
                                                                          at com.google.inject.Guice.createInjector(Guice.java:62)
                                                                          at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:124)
                                                                          at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
                                                                          at com.example.acer.prova.MainActivity.onCreate(MainActivity.java:21)
                                                                          at android.app.Activity.performCreate(Activity.java:6272)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                                       Caused by: com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
                                                                          at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:256)
                                                                          at com.google.inject.internal.cglib.core.$KeyFactory$Generator.create(KeyFactory.java:149)
                                                                          at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:117)
                                                                          at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:109)
                                                                          at com.google.inject.internal.cglib.core.$KeyFactory.create(KeyFactory.java:105)
                                                                          at com.google.inject.internal.cglib.core.$MethodWrapper.<clinit>(MethodWrapper.java:23)
                                                                          at com.google.inject.internal.cglib.core.$MethodWrapper.create(MethodWrapper.java:0) 
                                                                          at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:25) 
                                                                          at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52) 
                                                                          at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69) 
                                                                          at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77) 
                                                                          at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) 
                                                                          at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:231) 
                                                                          at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65) 
                                                                          at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:252) 
                                                                          at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:203) 
                                                                          at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:69) 
                                                                          at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275) 
                                                                          at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144) 
                                                                          at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123) 
                                                                          at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) 
                                                                          at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349) 
                                                                          at com.google.inject.spi.Elements.getElements(Elements.java:110) 
                                                                          at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) 
                                                                          at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) 
                                                                          at com.google.inject.Guice.createInjector(Guice.java:99) 
                                                                          at com.google.inject.Guice.createInjector(Guice.java:73) 
                                                                          at com.google.inject.Guice.createInjector(Guice.java:62) 
                                                                          at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:124) 
                                                                          at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58) 
                                                                          at com.example.acer.prova.MainActivity.onCreate(MainActivity.java:21) 
                                                                          at android.app.Activity.performCreate(Activity.java:6272) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5527) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:395)
                                                                          at com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:390)
                                                                      	at com.google.inject.internal.cgli
`

What could the cause be?
I'm really struggling since all of this is for an important project, I desperately need a clue.
Thanks in advance

**Comment by ignazio1977** [comment]
My best guess for what the stack trace is talking about is the guice-assistedinject function that creates factories. If so, it looks like this won't work in android. The apibinding module will need changing.

As a workaround, you could try to write your own version of OWLManager - it is the main class that needs changing. I don't have my laptop with me for the next ten days so I can't help much on that.

**Comment by ykazakov** [comment]
OWL API 3.x worked with Android fine. Here is a [project](https://github.com/liveontologies/elk-reasoner/tree/feature/android). Here is the resulting [app](https://www.dropbox.com/s/fxiq6w3mlsvlf0n/ElkReasoner.apk?dl=0).
