### ISSUE TITLE
SAXParserFactoryImpl not found

### ISSUE THREAD

**Issue by mikearmagedon** [owlcs/owlapi#665]
Hello,

I'm having a problem loading an ontology from a file.

Here's what I'm doing:
```
public static void LoadOntology(String importOnt) throws IOException
{	
	OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
	
	if (importOnt != null)
	{
		File ontFile = new File(importOnt);
		
		AutoIRIMapper automapper = new AutoIRIMapper(ontFile.getParentFile(), true);		
		manager.getIRIMappers().add(automapper);
		
		try {
			OWLOntology designFlow = manager.loadOntologyFromOntologyDocument(ontFile);
		} catch (OWLOntologyCreationException e) {
			throw new IOException("Error Loading Ontology: " + importOnt + " -> " + e.getMessage());
		}
		
		manager.getOntologies().forEach(o -> System.out.println(local_log + "Loaded " + o.getOntologyID().getOntologyIRI().get().toString() + " successfully."));
	}
}
```
Here's the error I'm getting which occurs when loadOntologyFromOntologyDocument method is called.
```
javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
	at javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
	at org.semanticweb.owlapi.util.SAXParsers.initFactory(SAXParsers.java:43)
	at org.semanticweb.owlapi.util.SAXParsers.initParserWithOWLAPIStandards(SAXParsers.java:66)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:140)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1061)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1017)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:967)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:978)
	at org.esrg.inference.engine.InferenceEngine.LoadOntology(InferenceEngine.java:56)
```

What I'm finding odd is that the file that I'm trying to load is in the OWL/XML format, but the OntologyManager somehow calls a RDFXML parser.

Is there a way for to force it to call an OWLXML parser?

**Comment by ignazio1977** [comment]
OWLOntologyDocumentSource source=new FileDocumentSource(ontFile, new OWLXMLDocumentFormat());
    OWLOntology designFlow = manager.loadOntologyFromOntologyDocument(source);

When the format is unspecified, the RDFXML parser is the first to be attempted. However, you're probably going to meet with the same problem with the OWLXML parser, as both rely on the same sax parser factory.

**Comment by mikearmagedon** [comment]
Thanks, I'll try that.

**Comment by mikearmagedon** [comment]
You we're right ignazio1977, I still have the same problem, but now it calls the OWLXMLParser

**Comment by ignazio1977** [comment]
Ok, so let's figure out where the exception is coming from. Which Java version are you using? It seems the SaxParserFactory class included in your JRE is not working properly.

**Comment by mikearmagedon** [comment]
Problem solved!
I had to add two required plugins to my eclipse project, those were:
 org.eclipse.core.resources;
 org.eclipse.core.runtime;

Now it's working.
Thanks for the help ignazio1977

**Comment by mikearmagedon** [comment]
I'm using Java 1.8 (java-8-openjdk-amd64)
