### ISSUE TITLE
Merge Error with AutoIRIMapper, OWLManager, and OWLOntologyMerger

### ISSUE THREAD

**Issue by ponnou** [owlcs/owlapi#671]
Hello,

I have two ontologies A, B
B -> imports A.
I would like to merge A and B in one Ontology C.

I am using the AutoIRIMapper to load them from the directory. 
First, I used AutoIRIMapper and OWLOntologyMerger to load and save. However the merge was empty!
```java
AutoIRIMapper mapper = new AutoIRIMapper(directory, true); 
owlManager.getIRIMappers().add(mapper);
```

then 
```java
OWLOntologyMerger merger = new OWLOntologyMerger(owlManager); 
IRI mergedOntologyIRI = IRI.create("", "MyMergedOnt"); 
OWLOntology merged = merger.createMergedOntology(owlManager, mergedOntologyIRI); 
File file = new File("C:\\MyMergedOntFile.owl"); 
owlManager.saveOntology(merged, IRI.create(file.toURI()));  
```
Then, I checked that the AutoIRIMapper don't have the ontologies that's why I keep having an empty merge.

So I used the OWLManager to load them again. 
```java
Stream<Path> paths = Files.walk(Paths.get(args[0])))
 {
 paths.forEach(filePath -> {
	if (Files.isRegularFile(filePath)) {
		File test_ontFile = new File(filePath.toString());
		owlManager.loadOntologyFromOntologyDocument(test_ontFile);
		});
     }
}
```

**My merge works well and as expected!** 
**However I have the following error:**

[main] ERROR uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl - OWLOntologyManagerImpl.checkForOntologyIDChange() existing:Ontology(OntologyID(OntologyIRI(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#>) VersionIRI(<null>))) [Axioms: 18 Logical Axioms: 8] First 20 axioms: {Declaration(ObjectProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#connectsToP>)) Declaration(DataProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#hasUnit>)) Declaration(DataProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#hasName>)) Declaration(ObjectProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#connectsTo>)) Declaration(ObjectProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#connectsToC>)) Declaration(DataProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#hasClassId>)) Declaration(Class(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#Source>)) Declaration(ObjectProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#connectsToAS>)) Declaration(ObjectProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#isConnectedBy>)) Declaration(DataProperty(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#hasType>)) InverseObjectProperties(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#connectsTo> <http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#isConnectedBy>) SubObjectPropertyOf(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#connectsToAS> owl:topObjectProperty) SubObjectPropertyOf(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#connectsToC> owl:topObjectProperty) SubObjectPropertyOf(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#connectsToP> owl:topObjectProperty) SubDataPropertyOf(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#hasClassId> owl:topDataProperty) SubDataPropertyOf(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#hasName> owl:topDataProperty) SubDataPropertyOf(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#hasType> owl:topDataProperty) SubClassOf(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#Source> DataSomeValuesFrom(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#hasType> xsd:string)) }
[main] ERROR uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl - OWLOntologyManagerImpl.checkForOntologyIDChange() new:Ontology(OntologyID(Anonymous-7)) [Axioms: 0 Logical Axioms: 0] First 20 axioms: {}
org.semanticweb.owlapi.model.OWLOntologyAlreadyExistsException: Ontology already exists. OntologyID(OntologyIRI(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#>) VersionIRI(<null>))
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1085)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1033)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:982)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:995)
	at semanticstore.ontology.library.generator.OntWalker.lambda$0(OntWalker.java:73)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at semanticstore.ontology.library.generator.OntWalker.main(OntWalker.java:68)
Caused by: org.semanticweb.owlapi.model.OWLOntologyRenameException: Could not rename ontology. An ontology with this ID already exists: OntologyID(OntologyIRI(<http://www.semanticweb.org/sesa443818/ontologies/2017/3/mother#>) VersionIRI(<null>))
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.checkForOntologyIDChange(OWLOntologyManagerImpl.java:729)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.enactChangeApplication(OWLOntologyManagerImpl.java:587)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actuallyApply(OWLOntologyManagerImpl.java:635)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChangesAndGetDetails(OWLOntologyManagerImpl.java:604)
	at org.semanticweb.owlapi.model.HasApplyChanges.applyChanges(HasApplyChanges.java:37)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChange(OWLOntologyManagerImpl.java:683)
	at org.semanticweb.owlapi.model.OWLOntology.applyChange(OWLOntology.java:90)
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.applyChange(ConcurrentOWLOntologyImpl.java:2342)
	at org.semanticweb.owlapi.owlxml.parser.OntologyEH.attribute(PARSER_OWLXMLVocabulary.java:1994)
	at org.semanticweb.owlapi.owlxml.parser.OWLXMLPH.startElement(OWLXMLPH.java:477)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.semanticweb.owlapi.owlxml.parser.OWLXMLParser.parse(OWLXMLParser.java:49)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:188)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1072)
	... 15 more

**Comment by ignazio1977** [comment]
The error derives likely from loading the same ontology twice; you are loading all ontologies manually from a folder in the second step, but some of the ontologies might have been loaded already in the first step, or have been imported already by a previous load.

Also, please specify which version of OWLAPI you are using. There have been fixes in the area of identifying duplicate loads, so it's possible that you've stumbled on a bug that has already been fixed.

**Comment by ignazio1977** [comment]
in OWLAPI 5, you should call `clearOntologies()` before attempting to reload all ontologies with the same manager, this will avoid duplicate ontologies causing this issue.
