### ISSUE TITLE
AtomicDecomposition throws Nullpointer

### ISSUE THREAD

**Issue by mrnolte** [owlcs/owlapi#695]
Hey there,
I tried to extract a module using the `AtomicDecomposition`. My code was
```
final OWLOntologyManager manager = OWLManager.createConcurrentOWLOntologyManager();
final OWLOntology ontology = manager.loadOntologyFromOntologyDocument(new File("enm.enanomapper.14.orig"));
final OWLOntology go = manager.getOntology(IRI.create("http://purl.enanomapper.org/onto/external/go-slim.owl"));
AtomicDecomposition atomicDecomposition = new AtomicDecompositionImpl(ontology, ModuleType.STAR);
if(go != null) {
   atomicDecomposition.getModule(go.signature(), false, ModuleType.STAR);
}
```
This will produce the following error:
```
Exception in thread "main" java.lang.NullPointerException
	at org.semanticweb.owlapitools.decomposition.Modularizer.addNonLocal(Modularizer.java:114)
	at org.semanticweb.owlapitools.decomposition.Modularizer.extractModuleQueue(Modularizer.java:134)
	at org.semanticweb.owlapitools.decomposition.Modularizer.extractModule(Modularizer.java:148)
	at org.semanticweb.owlapitools.decomposition.Modularizer.extract(Modularizer.java:177)
	at org.semanticweb.owlapitools.decomposition.Decomposer.getModule(Decomposer.java:243)
	at uk.ac.manchester.cs.atomicdecomposition.AtomicDecompositionImpl.getModule(AtomicDecompositionImpl.java:240)
```
The loaded Ontology can be found here [ontology.zip](https://github.com/owlcs/owlapi/files/1251556/ontology.zip) and originated here [https://zenodo.org/record/439510#.WZ_4rNFCSUk](url). The used OWL API version is 5.1.1.

Thanks for reading,
Robin Nolte

**Comment by ignazio1977** [comment]
Looks like that code is relying on the entity being used having been seen in the input ontology in at least one axiom. Instead of a null collection, an empty one should be returned.
