### ISSUE TITLE
Jena推理

### ISSUE THREAD

**Issue by JINGJiangbo** [owlcs/owlapi#731]
我用Jena解析protege构建的本体，但是出现了以下的问题，很奇怪，同样的本体有的实例可以分析出来，有的实例就报这个错误，望大神可以解答
Exception in thread "main" org.apache.jena.ontology.ConversionException: Cannot convert node http://www.w3.org/2002/07/owl#NamedIndividual to OntClass: it does not have rdf:type owl:Class or equivalent
	at org.apache.jena.ontology.impl.OntClassImpl$1.wrap(OntClassImpl.java:82)
	at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:152)
	at org.apache.jena.enhanced.EnhNode.convertTo(EnhNode.java:31)
	at org.apache.jena.enhanced.Polymorphic.asInternal(Polymorphic.java:62)
	at org.apache.jena.enhanced.EnhNode.as(EnhNode.java:107)
	at org.apache.jena.ontology.impl.IndividualImpl.getOntClass(IndividualImpl.java:174)
	at org.apache.jena.ontology.impl.IndividualImpl.getOntClass(IndividualImpl.java:148)
	at jena.jj.main(jj.java:244)

**Comment by ansell** [comment]
If you have a specific part of your ontology that you can't parse using OWLAPI, could you post the ontology and the code you are using to parse it using OWLAPI here?

However, it looks like this is a Jena issue, which you would need to submit as an issue on their tracker at https://issues.apache.org/jira/projects/JENA/issues

**Comment by ignazio1977** [comment]
Jena throws this sort of error when declarations are missing. In this case, `NamedIndividual` is a language level class, so it won't have a declaration. Not sure if that's intended behaviour - could it be that the OntModel has been built with the wrong profile?
