### ISSUE TITLE
 java.lang.IllegalArgumentException: Non-simple property 'ObjectInverseOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#isBaseOf>)' or its inverse appears in the cardinality restriction 'ObjectMaxCardinality(1 ObjectInverseOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#isBaseOf>) owl:Thing)'.

### ISSUE THREAD

**Issue by karanthpallavi** [owlcs/owlapi#738]
Hi,
Have invoked reasoner for the standard pizza ontology,
Am getting IllegalArgumentException,

Exception in thread "main" java.lang.IllegalArgumentException: Non-simple property 'ObjectInverseOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#isBaseOf>)' or its inverse appears in the cardinality restriction 'ObjectMaxCardinality(1 ObjectInverseOf(<http://www.co-ode.org/ontologies/pizza/pizza.owl#isBaseOf>) owl:Thing)'.
	at org.semanticweb.HermiT.structural.ObjectPropertyInclusionManager.rewriteAxioms(ObjectPropertyInclusionManager.java:118)
	at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:88)
	at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:210)
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:201)
	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:175)
	at org.semanticweb.HermiT.ReasonerFactory.createHermiTOWLReasoner(ReasonerFactory.java:51)
	at org.semanticweb.HermiT.ReasonerFactory.createReasoner(ReasonerFactory.java:19)
	at com.mycompany.semanticbetweennesscentrality.SemanticBetweennessCentrality.SemanticFiltering(SemanticBetweennessCentrality.java:320)
	at com.mycompany.semanticbetweennesscentrality.SemanticBetweennessCentrality.SemanticBetweennessCentrality(SemanticBetweennessCentrality.java:147)
	at com.mycompany.semanticbetweennesscentrality.SemanticBetweennessCentrality.loadOntology(SemanticBetweennessCentrality.java:126)
	at com.mycompany.semanticbetweennesscentrality.SemanticBetweennessCentrality.main(SemanticBetweennessCentrality.java:87)
------------------------------------------------------------------------
BUILD FAILURE

May i know what has to be done?
In the ontology, the property hasBase or isBaseOf is sub property of hasIngredient/isIngredientOf .
Have tried removing property sub property relation between hasBase and hasIngrdient,
Still the error persists,
Can anyone help how this can be resolved?
Wondering why we get errors for standard ontologies?

**Comment by ignazio1977** [comment]
isBaseOf should be used in place of inverseOf(hasBase).

The reasoner should have simplified the property before checking for violations.

On a separate topic, there is no such thing as standard ontologies - the pizza ontology is just an example.

**Comment by karanthpallavi** [comment]
Thanks for your quick response,
Will do that and try

**Comment by ignazio1977** [comment]
For the record, this does not happen with the latest HermiT and the pizza.owl version 2: https://raw.githubusercontent.com/owlcs/pizza-ontology/master/pizza.owl
