### ISSUE TITLE
Fuzzy OWL tab not working with Protege 5.2.0

### ISSUE THREAD

**Issue by ying6991** [owlcs/owlapi#750]
When I open the Fuzzy OWL tab, there is nothing on it. What should I do with it? 
Thanks,
Ying Zhang.
![tim 20180418202021](https://user-images.githubusercontent.com/26991546/38931980-7af2b644-4347-11e8-80e0-2d4815b0d3be.jpg)

**Comment by ignazio1977** [comment]
The Fuzzy OWL plugin is not part of the owlapi project. Is it hosted with Protege or on another repository? The developers of the plugin should be able to help you better than we do.

Do you get any specific error?

**Comment by ignazio1977** [comment]
protegewiki.stanford.edu/wiki/FuzzyOWL2
says it's compatible with Protege 4.1. Do you have a source that states it's compatible with 5.2?

**Comment by ying6991** [comment]
@ignazio1977 The same situation is displayed using Protege 4.1. Thanks.
![tim 20180418205222](https://user-images.githubusercontent.com/26991546/38933026-6e402898-434a-11e8-8e85-cf1e1295af4a.jpg)

**Comment by ignazio1977** [comment]
Do you get any errors on the Protege console?

**Comment by ying6991** [comment]
Error 5 Logged at Thu Apr 19 09:14:19 CST 2018
UnsupportedClassVersionError: Bad version number in .class file
    java.lang.ClassLoader.defineClass1(Native Method)
    java.lang.ClassLoader.defineClass(Unknown Source)
    org.apache.felix.framework.ModuleImpl$ModuleClassLoader.findClass(ModuleImpl.java:1872)
    org.apache.felix.framework.ModuleImpl.findClassOrResourceByDelegation(ModuleImpl.java:758)
    org.apache.felix.framework.ModuleImpl.access$100(ModuleImpl.java:61)
    org.apache.felix.framework.ModuleImpl$ModuleClassLoader.loadClass(ModuleImpl.java:1733)
    java.lang.ClassLoader.loadClass(Unknown Source)
    org.apache.felix.framework.ModuleImpl.getClassByDelegation(ModuleImpl.java:674)
    org.apache.felix.framework.Felix.loadBundleClass(Felix.java:1543)
    org.apache.felix.framework.BundleImpl.loadClass(BundleImpl.java:887)
    org.protege.editor.core.plugin.PluginUtilities.getExtensionObject(PluginUtilities.java:131)
    org.protege.editor.core.plugin.ExtensionInstantiator.instantiate(ExtensionInstantiator.java:74)
    org.protege.editor.core.ui.view.ViewComponentPluginJPFImpl.newInstance(ViewComponentPluginJPFImpl.java:131)
    org.protege.editor.core.ui.view.ViewComponentPluginJPFImpl.newInstance(ViewComponentPluginJPFImpl.java:46)
    org.protege.editor.core.ui.view.View.createContent(View.java:431)
    org.protege.editor.core.ui.view.View.createUI(View.java:214)
    org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:144)
    java.awt.Component.processHierarchyEvent(Unknown Source)
    java.awt.Component.processEvent(Unknown Source)
    java.awt.Container.processEvent(Unknown Source)
    java.awt.Component.dispatchEventImpl(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.Component.createHierarchyEvents(Unknown Source)
    java.awt.Container.createHierarchyEvents(Unknown Source)
    java.awt.Container.createHierarchyEvents(Unknown Source)
    java.awt.Container.createHierarchyEvents(Unknown Source)
    java.awt.Container.createHierarchyEvents(Unknown Source)
    java.awt.Container.createHierarchyEvents(Unknown Source)
    java.awt.Component.show(Unknown Source)
    java.awt.Component.show(Unknown Source)
    java.awt.Component.setVisible(Unknown Source)
    javax.swing.JComponent.setVisible(Unknown Source)
    javax.swing.plaf.basic.BasicTabbedPaneUI.setVisibleComponent(Unknown Source)
    javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.layoutContainer(Unknown Source)
    java.awt.Container.layout(Unknown Source)
    java.awt.Container.doLayout(Unknown Source)
    java.awt.Container.validateTree(Unknown Source)
    java.awt.Container.validateTree(Unknown Source)
    java.awt.Container.validate(Unknown Source)
    javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
    javax.swing.SystemEventQueueUtilities$ComponentWorkRequest.run(Unknown Source)
    java.awt.event.InvocationEvent.dispatch(Unknown Source)
    java.awt.EventQueue.dispatchEvent(Unknown Source)
    java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.run(Unknown Source)
---------------------------------------------------------------------------------------------------

**Comment by faiqpurnomo** [comment]
Hi, I have the same exact problem, does anyone know how to solve it? Thank you

**Comment by thomakl** [comment]
Hi,
have pretty much the sam problem, does anyone know how to solve it?
Thank you

`[AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoSuchMethodError: org.semanticweb.owlapi.model.OWLOntologyID.getOntologyIRI()Lorg/semanticweb/owlapi/model/IRI;
	at FuzzyOWL2Plugin.FuzzyDLReasonerQueryPanel.<init>(FuzzyDLReasonerQueryPanel.java:67) ~[na:na]
	at FuzzyOWL2Plugin.FuzzyOWL2Plugin.initialiseOWLView(FuzzyOWL2Plugin.java:1596) ~[na:na]
	at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:43) ~[na:na]
	at org.protege.editor.core.ui.view.View.createContent(View.java:413) ~[na:na]
	at org.protege.editor.core.ui.view.View.createUI(View.java:220) ~[na:na]
	at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:124) ~[na:na]
	at java.awt.Component.processHierarchyEvent(Component.java:6700) ~[na:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6319) ~[na:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.Component.createHierarchyEvents(Component.java:5549) ~[na:1.8.0_121]
	at java.awt.Container.createHierarchyEvents(Container.java:1445) ~[na:1.8.0_121]
	at java.awt.Container.createHierarchyEvents(Container.java:1441) ~[na:1.8.0_121]
	at java.awt.Container.createHierarchyEvents(Container.java:1441) ~[na:1.8.0_121]
	at java.awt.Container.createHierarchyEvents(Container.java:1441) ~[na:1.8.0_121]
	at java.awt.Container.createHierarchyEvents(Container.java:1441) ~[na:1.8.0_121]
	at java.awt.Component.show(Component.java:1639) ~[na:1.8.0_121]
	at java.awt.Component.show(Component.java:1671) ~[na:1.8.0_121]
	at java.awt.Component.setVisible(Component.java:1623) ~[na:1.8.0_121]
	at javax.swing.JComponent.setVisible(JComponent.java:2644) ~[na:1.8.0_121]
	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394) ~[na:1.8.0_121]
	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) ~[na:1.8.0_121]
	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) ~[na:1.8.0_121]
	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) ~[na:1.8.0_121]
	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) ~[na:1.8.0_121]
	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591) ~[na:1.8.0_121]
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) ~[na:1.8.0_121]
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) ~[na:1.8.0_121]
	at java.awt.Component.processMouseEvent(Component.java:6530) ~[na:1.8.0_121]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6298) ~[na:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_121]`

Runing Protege 5.5.0 Mac OS X 10.11
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

By the way do you know exactly where to put the folder "dlib" in the Protégé folder ?

Best regards,

**Comment by ignazio1977** [comment]
It's not the same error.
The previous one was a JVM issue, this is a conflict between the OWLAPI version used by protégé 5 and the one used by fuzzy owl. Looks like they're using an earlier major version. To fix, fuzzy owl must be updated to use OWLAPI version 4.
