### ISSUE TITLE
ConcurrentModificationException while add axioms from a stream of axioms produce by owlapi.

### ISSUE THREAD

**Issue by Galigator** [owlcs/owlapi#754]
Hello,

I have run into this exception very rarely but it's look like it shouldn't at all.
I am asking if it is the expected behaviour knowing my setup :

```
 java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1386)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.semanticweb.owlapi.util.OWLAPIStreamUtils.asList(OWLAPIStreamUtils.java:190)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.addAxioms(OWLOntologyManagerImpl.java:672)
[ ... my code ...]

```

**setup** : 
I have encountered this exception with the 5.1.4. 

 The stream of axioms I try to insert  is build from a stream of axioms from the same ontology. The logical operation I am doing is near from being  "cloning an individual with its property" with a few differences (time versionning). So there is a relation between the the axioms I am reading and the axioms I writing : Like a temporal relation (https://www.w3.org/TR/owl-time/) between the original and the clone individual.

**workaround**:
It is a very rare exception; the main program use only two concurrent threads, but it may use more in future.
For the moment, my way to go is to copy the stream into a list and then insert axioms from the list when fully build.

Regards,
Galigator.

**Comment by ignazio1977** [comment]
Your workaround is the best solution. The problem is that the stream won't make a copy of the collection, to save the effort of making the copy - but, of course, this comes at the expense of not modifying the collection until the streaming is over. It's the same tradeoff as modifying a collection while an iterator on it is open.

The only way owlapi can avoid that is by always creating a list containing all axioms before returning a stream - it's what we did before streams. It comes at a performance cost, and if we do it in the library the caller has to pay the price whether they make changes or not.

**Comment by Galigator** [comment]
Thank you Ignazio,

that what I expected.
I will keep my workaround in place.
The price isn't to mush for me, the reasoning that come before and after the 'clone' cost a lot more.

Regards,
Galigator.
