### ISSUE TITLE
ReadWriteLock should be shared between manager and its ontologies

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#785]
After upgrading from 5.1.5 to 5.1.6/5.1.7 I see that test, which checks sharing R/W Lock for concurrent manager is failed.

It is [OWLManagerTestCase](https://github.com/owlcs/owlapi/blob/version5/contract/src/test/java/org/semanticweb/owlapi/api/test/OWLManagerTestCase.java) testcase, but with ConcurrentManager:

```
package test;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl;
import uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl;

import java.lang.reflect.Field;
import java.util.Objects;

public class OWLAPIManagerTest {
    private static final Logger LOGGER = LoggerFactory.getLogger(OWLAPIManagerTest.class);

    public static void main(String ... args) throws Exception {
        LOGGER.info("Start");
        OWLOntologyManager m = OWLManager.createConcurrentOWLOntologyManager();
        LOGGER.debug("Manager: {}", m);
        OWLOntology o = m.createOntology();
        LOGGER.debug("Ontology: {}", o);
        shouldShareReadWriteLock(m, o);
        LOGGER.info("OK");
    }

    private static void shouldShareReadWriteLock(OWLOntologyManager manager, OWLOntology ontology) throws Exception {
        Field ontologyLockField = ConcurrentOWLOntologyImpl.class.getDeclaredField("readLock");
        ontologyLockField.setAccessible(true);
        Field ontologyManagerField = OWLOntologyManagerImpl.class.getDeclaredField("readLock");
        ontologyManagerField.setAccessible(true);
        assertSame(ontologyLockField.get(ontology), ontologyManagerField.get(manager));
        ontologyLockField = ConcurrentOWLOntologyImpl.class.getDeclaredField("writeLock");
        ontologyLockField.setAccessible(true);
        ontologyManagerField = OWLOntologyManagerImpl.class.getDeclaredField("writeLock");
        ontologyManagerField.setAccessible(true);
        assertSame(ontologyLockField.get(ontology), ontologyManagerField.get(manager));
    }

    private static void assertSame(Object expected, Object actual) {
        if (Objects.equals(expected, actual)) return;
        throw new AssertionError("Not equal objects: " + expected + " != " + actual);
    }
}
```
Output:

```
[ INFO][OWLAPIManagerTest] 12:45:07.215 Start
[ INFO][Injector] 12:45:07.345 Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyManager
[ INFO][Injector] 12:45:07.375 Loading file META-INF/services/org.semanticweb.owlapi.model.OWLDataFactory
[ INFO][Injector] 12:45:07.645 Injecting object uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl@5c18298f
[ INFO][Injector] 12:45:07.675 Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyIRIMapper
[ WARN][Injector] 12:45:07.675 No files found for META-INF/services/org.semanticweb.owlapi.model.OWLOntologyIRIMapper
[ INFO][Injector] 12:45:07.685 Injecting values [[]] on method public void uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setIRIMappers(java.util.Set).
[ INFO][Injector] 12:45:07.685 Loading file META-INF/services/org.semanticweb.owlapi.io.OWLParserFactory
[ INFO][Injector] 12:45:07.715 Injecting values [[org.semanticweb.owlapi.rio.RioBinaryRdfParserFactory@6328d34a, org.semanticweb.owlapi.krss2.parser.KRSS2OWLParserFactory@16267862, org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxOWLParserFactory@6e38921c, org.semanticweb.owlapi.rio.RioNTriplesParserFactory@3bbc39f8, org.semanticweb.owlapi.rio.RioTrigParserFactory@40e6dfe1, org.semanticweb.owlapi.dlsyntax.parser.DLSyntaxOWLParserFactory@797badd3, org.semanticweb.owlapi.rio.RioRDFaParserFactory@589b3632, org.semanticweb.owlapi.rio.RioTrixParserFactory@123f1134, org.semanticweb.owlapi.rio.RioNQuadsParserFactory@52aa2946, org.semanticweb.owlapi.rio.RioRDFXMLParserFactory@35083305, org.semanticweb.owlapi.rio.RioJsonLDParserFactory@4c40b76e, org.semanticweb.owlapi.rio.RioTurtleParserFactory@25b485ba, org.semanticweb.owlapi.rdf.turtle.parser.TurtleOntologyParserFactory@49e202ad, org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParserFactory@ba8d91c, org.semanticweb.owlapi.owlxml.parser.OWLXMLParserFactory@38364841, org.semanticweb.owlapi.rio.RioN3ParserFactory@64c87930, org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxOntologyParserFactory@6c3f5566, org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParserFactory@15d9bc04, org.semanticweb.owlapi.rio.RioJsonParserFactory@667a738]] on method public void uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyParsers(java.util.Set).
[ INFO][Injector] 12:45:07.715 Loading file META-INF/services/org.semanticweb.owlapi.model.OWLOntologyFactory
[ INFO][Injector] 12:45:07.715 Injecting values [[uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl@548a102f]] on method public void uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyFactories(java.util.Set).
[ INFO][Injector] 12:45:07.715 Loading file META-INF/services/org.semanticweb.owlapi.model.OWLStorerFactory
[ INFO][Injector] 12:45:07.725 Injecting values [[org.semanticweb.owlapi.rio.RioTrixStorerFactory@1460a8c0, org.semanticweb.owlapi.rio.RioNTriplesStorerFactory@fdefd3f, org.semanticweb.owlapi.manchestersyntax.renderer.ManchesterSyntaxStorerFactory@48524010, org.semanticweb.owlapi.rdf.turtle.renderer.TurtleStorerFactory@3b2da18f, org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxHTMLStorerFactory@143640d5, org.semanticweb.owlapi.rio.RioN3StorerFactory@3745e5c6, org.semanticweb.owlapi.dlsyntax.renderer.DLSyntaxStorerFactory@657c8ad9, org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxStorerFactory@53ca01a2, org.semanticweb.owlapi.rio.RioRDFXMLStorerFactory@11dc3715, org.semanticweb.owlapi.krss2.renderer.KRSS2OWLSyntaxStorerFactory@23282c25, org.semanticweb.owlapi.latex.renderer.LatexStorerFactory@3b938003, org.semanticweb.owlapi.rio.RioNQuadsStorerFactory@19d37183, org.semanticweb.owlapi.rdf.rdfxml.renderer.RDFXMLStorerFactory@161b062a, org.semanticweb.owlapi.rio.RioJsonLDStorerFactory@7c417213, org.semanticweb.owlapi.oboformat.OBOFormatStorerFactory@2aa5fe93, org.semanticweb.owlapi.rio.RioBinaryRdfStorerFactory@3e3047e6, org.semanticweb.owlapi.rio.RioTrigStorerFactory@78047b92, org.semanticweb.owlapi.rio.RioJsonStorerFactory@327b636c, org.semanticweb.owlapi.owlxml.renderer.OWLXMLStorerFactory@4034c28c, org.semanticweb.owlapi.rio.RioTurtleStorerFactory@6e75aa0d]] on method public void uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyStorers(java.util.Set).
[DEBUG][OWLAPIManagerTest] 12:45:07.735 Manager: uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl@5c18298f
[DEBUG][OWLAPIManagerTest] 12:45:07.815 Ontology: Ontology(OntologyID(Anonymous-0)) [Axioms: 0 Logical Axioms: 0] First 20 axioms: {}
Exception in thread "main" java.lang.AssertionError: Not equal objects: java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock@333291e3[Read locks = 0] != java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock@479d31f3[Read locks = 0]
	at test.OWLAPIManagerTest.assertSame(OWLAPIManagerTest.java:42)
	at test.OWLAPIManagerTest.shouldShareReadWriteLock(OWLAPIManagerTest.java:32)
	at test.OWLAPIManagerTest.main(OWLAPIManagerTest.java:23)
```
Pom snippet:

```
    <properties>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.owlapi>5.1.7</version.owlapi>
        <version.slf4j>1.7.25</version.slf4j>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-api</artifactId>
            <version>${version.owlapi}</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-impl</artifactId>
            <version>${version.owlapi}</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-apibinding</artifactId>
            <version>${version.owlapi}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${version.slf4j}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${version.slf4j}</version>
        </dependency>
    </dependencies>
```

**Comment by ignazio1977** [comment]
Must be a bug in the injection. Thanks for reporting, I'll investigate.

**Comment by ignazio1977** [comment]
Before the Guice dependency was removed, the lock instance would be a singleton at injector level, and the default behaviour was to have only two injectors in OWLManager, one for concurrent and one for non concurrent access. The removal of the guice dependency made the locks into prototype level instances (to use Spring terms). All ontologies created by a manager share the same lock, as it is injected in the ontology builder object, of which there is only one instance for each manager; but the lock used by the manager itself, for operations such as adding and removing ontologies, is injected in the manager independently of the ontology builder, thus causing the problem.

A proper fix would be for manager and ontology builder to use the same lock, instead of each having a constructor accepting a lock, but this would require interface changes. A kludgier solution, but one that can be backported to v4, is to replicate the injector level singleton strategy that existed before.

I'm not entirely sure if one lock across all managers was the original design intention - I feel a manager level lock for all ontologies belonging to the manager might be closer to what was originally needed. However, restoring the status quo is better than a different failure mode.
