### ISSUE TITLE
Concurrent managers should have own lock and share it with their own ontologies

### ISSUE THREAD

**Issue by matthewhorridge** [owlcs/owlapi#806]
With reference to 4.5.6, the lock for concurrent impls is shared between OWLOntologyManager objects (the lock is held in a static field).  Is this intended/correct @ignazio1977?

I'm getting problems when concurrently creating new managers and accessing existing managers/ontologies.  

Here's a typical stack trace

```java
- parking to wait for <0x00000001c2382918> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(java.base@11.0.1/LockSupport.java:194)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.1/AbstractQueuedSynchronizer.java:885)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.1/AbstractQueuedSynchronizer.java:917)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.1/AbstractQueuedSynchronizer.java:1240)
at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(java.base@11.0.1/ReentrantReadWriteLock.java:959)
at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentPriorityCollection.clear(ConcurrentPriorityCollection.java:135)
at org.semanticweb.owlapi.util.PriorityCollection.set(PriorityCollection.java:81)
at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setIRIMappers(OWLOntologyManagerImpl.java:1561)
at jdk.internal.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.1/DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(java.base@11.0.1/Method.java:566)
at org.semanticweb.owlapi.utilities.Injector.inject(Injector.java:215)
at org.semanticweb.owlapi.apibinding.OWLManager.createConcurrentOWLOntologyManager(OWLManager.java:117)
```

**Comment by matthewhorridge** [comment]
Related issue

https://github.com/owlcs/owlapi/issues/785

**Comment by ignazio1977** [comment]
In #785 I mentioned how - as far as I could tell - the lock ended up being one across all managers because there were only two injector instances. I believe this behaviour was introduced when we changed the injector creation strategy for performance reasons.

I don't think it's correct - I think the lock should be manager level, not static. However, at the time I didn't have a good solution. I'll see if I can figure a good one out now.

**Comment by matthewhorridge** [comment]
>  I believe this behaviour was introduced when we changed the injector creation strategy for performance reasons.

Makes sense.  I'm pretty sure that it was not like this originally.

> I don't think it's correct - I think the lock should be manager level, not static. However, at the time I didn't have a good solution. I'll see if I can figure a good one out now.

Okay.  No worries.  I'm using Dagger for DI so I'm probably going to do something that works with that (have an OWL API module most probably).

**Comment by ignazio1977** [comment]
I'm not entirely pleased with this solution because it does not completely cover third party implementations, but we can't do better without an interface change.
