### ISSUE TITLE
EOFException in CustomTokenizer

### ISSUE THREAD

**Issue by rwynne** [owlcs/owlapi#813]
I am able to load my OWL file fine with 5.1.4.  The same file loaded with 5.1.8

`ontology = manager.loadOntologyFromOntologyDocument(new File(filename))`

Throws

Dec 31, 2018 1:32:38 PM org.semanticweb.owlapi.functional.parser.CustomTokenizer getNextToken
WARNING: Error reading from functional stream
java.io.EOFException
	at org.semanticweb.owlapi.functional.parser.CustomTokenizer.readChar(CustomTokenizer.java:439)
	at org.semanticweb.owlapi.functional.parser.CustomTokenizer.findTokenStart(CustomTokenizer.java:405)
	at org.semanticweb.owlapi.functional.parser.CustomTokenizer.getNextToken(CustomTokenizer.java:36)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.jj_consume_token(OWLFunctionalSyntaxParser.java:2397)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxParser.parse(OWLFunctionalSyntaxParser.java:102)
	at org.semanticweb.owlapi.functional.parser.OWLFunctionalSyntaxOWLParser.parse(OWLFunctionalSyntaxOWLParser.java:47)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:194)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1079)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1040)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:990)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1003)

**Comment by ignazio1977** [comment]
That's not a new exception being thrown. The exception was thrown in the previous version as well, and ignored. In the latest version, it is logged at WARN level. Parsing is not affected, however I'd like to see the last few lines of this file to ensure there isn't an actual issue being ignored.

**Comment by rwynne** [comment]
AnnotationAssertion(rdfs:label :9996003 "Arthrotomy with drainage of tarsometatarsal joint (procedure)"^^xsd:string)
EquivalentClasses(:9996003 ObjectIntersectionOf(:302495003 :56783008 ObjectSomeValuesFrom(:609096000 ObjectIntersectionOf(ObjectSomeValuesFrom(:260686004 :129287005) ObjectSomeValuesFrom(:405813007 :52741001))) ObjectSomeValuesFrom(:609096000 ObjectIntersectionOf(ObjectSomeValuesFrom(:260686004 :129289008) ObjectSomeValuesFrom(:363701004 :105590001) ObjectSomeValuesFrom(:405814001 :52741001)))))

AnnotationAssertion(rdfs:label :9998002 "Rumex venosus (organism)"^^xsd:string)
SubClassOf(:9998002 :17272006)

AnnotationAssertion(rdfs:label :9999005 "Duodenal ampulla structure (body structure)"^^xsd:string)
SubClassOf(:9999005 :56734009)


SubClassOf(ObjectIntersectionOf(:420134006 ObjectSomeValuesFrom(:609096000 ObjectSomeValuesFrom(:719722006 :472963003))) :473010000)
SubClassOf(ObjectIntersectionOf(:420134006 ObjectSomeValuesFrom(:609096000 ObjectSomeValuesFrom(:719722006 :472964009))) :473011001)
SubClassOf(ObjectIntersectionOf(:64572001 ObjectSomeValuesFrom(:609096000 ObjectSomeValuesFrom(:370135005 :472963003))) :473010000)
SubClassOf(ObjectIntersectionOf(:64572001 ObjectSomeValuesFrom(:609096000 ObjectSomeValuesFrom(:370135005 :472964009))) :473011001)
SubObjectPropertyOf(ObjectPropertyChain(:127489000 :738774007) :127489000)
SubObjectPropertyOf(ObjectPropertyChain(:246075003 :738774007) :246075003)
SubObjectPropertyOf(ObjectPropertyChain(:246093002 :738774007) :246093002)
SubObjectPropertyOf(ObjectPropertyChain(:363701004 :738774007) :363701004)
SubObjectPropertyOf(ObjectPropertyChain(:424361007 :738774007) :424361007)
AnnotationAssertion(rdfs:label :762706009 "Concept model data attribute (attribute)"^^xsd:string)
)

**Comment by HansBrende** [comment]
@ignazio1977 I'm getting the same error being logged since 5.1.8 with the following test file:

> Prefix(:=<http://example.org/example-manchestersyntax#>)
> 
> Ontology( <http://example.org/example-manchestersyntax>
>   AnnotationAssertion( rdfs:comment :TestIndividual "Test individual is a unique individual" )
> )

**Comment by ignazio1977** [comment]
The logging is only noise, it warns of having reached the end of file in all cases - whether it's expected or premature. Ignore it - it's only relevant if an exception is thrown from the parser. I'll remove it in the next release.
