### ISSUE TITLE
OWLManager error in 5.1.4 using elk-owlapi5

### ISSUE THREAD

**Issue by rwynne** [owlcs/owlapi#841]
Looks like Elk has changed something (0.5.0-SNAPSHOT) with a conflicting class in the owlapi.  After updating my maven project today, the OWLManager is now unable to load my unchanged ontology.

(@ignazio1977 - If you think this warrants an issue in the Elk project, holler.)

pom
```
 <dependencies>
      <dependency>
      <groupId>net.sourceforge.owlapi</groupId>
      <artifactId>owlapi-distribution</artifactId>
      <version>5.1.4</version>
    </dependency>
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20180130</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-jdk14</artifactId>
      <version>1.7.25</version>
    </dependency>
    <dependency> 
       <groupId>org.semanticweb.elk</groupId> 
       <artifactId>elk-owlapi5</artifactId> 
       <version>0.5.0-SNAPSHOT</version> 
    </dependency>
	<dependency>
	    <groupId>org.apache.poi</groupId>
	    <artifactId>poi</artifactId>
	    <version>3.17</version>
	</dependency>  
	<dependency>
	    <groupId>org.apache.commons</groupId>
	    <artifactId>commons-lang3</artifactId>
    	<version>3.8.1</version>
	</dependency>
 </dependencies>`
```

Call
```		try {
			man = OWLManager.createOWLOntologyManager();			
			ontology = man.loadOntologyFromOntologyDocument(new File(filename));
		} catch (OWLOntologyCreationException e1 ) {
			System.out.println("Not sure what could be happening here all of a sudden.");
			e1.printStackTrace();
		}
```

New exception
```
Apr 18, 2019 4:32:19 PM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.NoSuchMethodException: uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.<init>()
org.semanticweb.owlapi.model.OWLRuntimeException: Injection failed for interface org.semanticweb.owlapi.model.OWLOntologyFactory
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadInstancesFromServiceLoader(OWLAPIServiceLoaderModule.java:62)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(OWLAPIServiceLoaderModule.java:49)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:104)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:44)
	at gov.nih.nlm.mor.map.GenerateEquivalenciesSnomedClasses.<init>(GenerateEquivalenciesSnomedClasses.java:172)
	at gov.nih.nlm.mor.map.MapRxNormToSnomed.run(MapRxNormToSnomed.java:226)
	at gov.nih.nlm.mor.map.MapRxNormToSnomed.main(MapRxNormToSnomed.java:96)
Caused by: java.util.ServiceConfigurationError: org.semanticweb.owlapi.model.OWLOntologyFactory: Provider uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl could not be instantiated
	at java.util.ServiceLoader.fail(Unknown Source)
	at java.util.ServiceLoader.access$100(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
	at java.util.ServiceLoader$1.next(Unknown Source)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.load(OWLAPIServiceLoaderModule.java:86)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadInstancesFromServiceLoader(OWLAPIServiceLoaderModule.java:60)
	... 14 more
Caused by: java.lang.InstantiationException: uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl
	at java.lang.Class.newInstance(Unknown Source)
	... 20 more
Caused by: java.lang.NoSuchMethodException: uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.<init>()
	at java.lang.Class.getConstructor0(Unknown Source)
	... 21 more

Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.util.Set<org.semanticweb.owlapi.io.OWLParserFactory> was bound.
  while locating java.util.Set<org.semanticweb.owlapi.io.OWLParserFactory>
    for the 1st parameter of uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyParsers(OWLOntologyManagerImpl.java:1423)
  at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyParsers(OWLOntologyManagerImpl.java:1423)
  at uk.ac.manchester.cs.owl.owlapi.OWLAPIImplModule.configure(Unknown Source)

2) No implementation for java.util.Set<org.semanticweb.owlapi.model.OWLOntologyIRIMapper> was bound.
  while locating java.util.Set<org.semanticweb.owlapi.model.OWLOntologyIRIMapper>
    for the 1st parameter of uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setIRIMappers(OWLOntologyManagerImpl.java:1374)
  at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setIRIMappers(OWLOntologyManagerImpl.java:1374)
  at uk.ac.manchester.cs.owl.owlapi.OWLAPIImplModule.configure(Unknown Source)

3) No implementation for java.util.Set<org.semanticweb.owlapi.model.OWLStorerFactory> was bound.
  while locating java.util.Set<org.semanticweb.owlapi.model.OWLStorerFactory>
    for the 1st parameter of uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyStorers(OWLOntologyManagerImpl.java:1361)
  at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.setOntologyStorers(OWLOntologyManagerImpl.java:1361)
  at uk.ac.manchester.cs.owl.owlapi.OWLAPIImplModule.configure(Unknown Source)

4) An exception was caught and reported. Message: Injection failed for interface org.semanticweb.owlapi.model.OWLOntologyFactory
  at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(Unknown Source)

4 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:104)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:44)
	at gov.nih.nlm.mor.map.GenerateEquivalenciesSnomedClasses.<init>(GenerateEquivalenciesSnomedClasses.java:172)
	at gov.nih.nlm.mor.map.MapRxNormToSnomed.run(MapRxNormToSnomed.java:226)
	at gov.nih.nlm.mor.map.MapRxNormToSnomed.main(MapRxNormToSnomed.java:96)
Caused by: org.semanticweb.owlapi.model.OWLRuntimeException: Injection failed for interface org.semanticweb.owlapi.model.OWLOntologyFactory
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadInstancesFromServiceLoader(OWLAPIServiceLoaderModule.java:62)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(OWLAPIServiceLoaderModule.java:49)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 8 more
Caused by: java.util.ServiceConfigurationError: org.semanticweb.owlapi.model.OWLOntologyFactory: Provider uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl could not be instantiated
	at java.util.ServiceLoader.fail(Unknown Source)
	at java.util.ServiceLoader.access$100(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
	at java.util.ServiceLoader$1.next(Unknown Source)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.load(OWLAPIServiceLoaderModule.java:86)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadInstancesFromServiceLoader(OWLAPIServiceLoaderModule.java:60)
	... 14 more
Caused by: java.lang.InstantiationException: uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl
	at java.lang.Class.newInstance(Unknown Source)
	... 20 more
Caused by: java.lang.NoSuchMethodException: uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.<init>()
	at java.lang.Class.getConstructor0(Unknown Source)
	... 21 more
```

**Comment by rwynne** [comment]
Maybe the Elk pom change 29 days ago?

https://github.com/liveontologies/elk-reasoner/commit/f53773d71f782320cf73eb3d85ebfd4a32c941b3#diff-600376dffeb79835ede4a0b285078036

**Comment by rwynne** [comment]
Updating the owlapi dependency to 5.1.10 does not throw the exception, and seems to be the proper workaround?

**Comment by ignazio1977** [comment]
Indeed, newer OWLAPI dependency is the correct solution.
