### ISSUE TITLE
Null pointers with imports and relation declarations

### ISSUE THREAD

**Issue by cmungall** [owlcs/owlapi#859]
This is an incomplete bug report, I will try and whittle down to something more reproducible.

Sometimes a roundtrip from obo->obo will fail if not all relations have labels declared. This is in itself is odd, but this can interact with import statements in ways that don't see to make any sense.

The end result is a stacktrace such as:

```
Exception in thread "main" java.lang.NullPointerException
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1739)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI_load(OWLAPIObo2Owl.java:1679)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1643)
        at org.obolibrary.oboformat.writer.OBOFormatWriter$OWLOntologyNameProvider.getName(OBOFormatWriter.java:992)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer$1.getName(OBOFormatRenderer.java:74)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:622)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:155)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:119)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1525)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1502)
        at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:289)
        at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:209)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3712)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
```

apologies, this is my code from way back..

I know @dosumis has seen this too, cc @balhoff @matentzn 

More info as I accumulate it...

**Comment by cmungall** [comment]
OK, here is a test case.

main file:

```
ontology: uberon
import: http://purl.obolibrary.org/obo/uberon/test_import.owl

[Term]
id: X:1
name: x1
property_value: part_of X:2

[Typedef]
id: part_of
xref: BFO:0000050
```

catalog-v001.xml has:

```
    <uri id="User Entered Import Resolution" name="http://purl.obolibrary.org/obo/uberon/test_import.owl" uri="test_import.owl"/>
```

test_import is empty:

```
<?xml version="1.0"?>
<rdf:RDF
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/uberon/test_import.owl"/>
</rdf:RDF>
```

This causes the stack trace
`robot -vvv convert -i test.obo -o out.obo`

But note that removal of the import fixes this...

**Comment by cmungall** [comment]
Here is another odd example:

```
format-version: 1.2
import: http://purl.obolibrary.org/obo/uberon/pato_import.owl
ontology: uberon/core

[Term]
id: UBERON:0004138
name: somitomeric trunk muscle
property_value: seeAlso "string"

[Typedef]
id: seeAlso
name: seeAlso
is_metadata_tag: true
is_class_level: true
```

Note that in obo format, property_value can have 2 or 3 args. If it has 3 args, it's treated as literal, and the 2nd arg should be quoted. If it has 2 args, then arg2 is interpreted as an IRI

In this case what is odd is that if the imports is *not* present then arg 2 is dequoted and this generates a triple

```
        <core:seeAlso rdf:resource="http://purl.obolibrary.org/obo/uberon/core#string"/>
```

however, if the import *is* present then it will generate the stacktrace:

```
Exception in thread "main" java.lang.NullPointerException
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1739)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI_load(OWLAPIObo2Owl.java:1679)
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.oboIdToIRI(OWLAPIObo2Owl.java:1643)
        at org.obolibrary.oboformat.writer.OBOFormatWriter$OWLOntologyNameProvider.getName(OBOFormatWriter.java:992)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer$1.getName(OBOFormatRenderer.java:74)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:622)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
        at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:88)
        at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:42)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:155)
        at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:119)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1525)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1502)
        at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:289)
        at owltools.io.ParserWrapper.saveOWL(ParserWrapper.java:209)
        at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3712)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
        at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
        at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
```

**Comment by ignazio1977** [comment]
I've found the reason for the exception - when setting up name providers, there are two name providers, a primary and a secondary. The secondary one is only used when imports exist and the primary cannot find a name; however, both need access to the obo document. The primary had access to it, the secondary was built without setting the document. Hence the null pointer.

**Comment by ignazio1977** [comment]
Can I ask for clarification on one point:

> arg 2 is dequoted and this generates a triple
>
>        <core:seeAlso rdf:resource="http://purl.obolibrary.org/obo/uberon/core#string"/>

This is the *desired* behaviour, right?

**Comment by matentzn** [comment]
In which OWL API release was this fixed @ignazio1977 was it after `4.5.6`?

**Comment by ignazio1977** [comment]
@matentzn it was 4.5.14

**Comment by matentzn** [comment]
Thanks!
