### ISSUE TITLE
Exception when converting obi to obo

### ISSUE THREAD

**Issue by fanavarro** [owlcs/owlapi#860]
Hi all, I am trying to convert [obi ontology](http://purl.obolibrary.org/obo/obi.owl) to obo format by means of owlapi. I am using the latest owlapi code in github (version 5.1.11). I have the following method:
 ```
 public static void convertToObo(File inputFile, File outputFile) throws OWLOntologyCreationException, OWLOntologyStorageException {
    /* Create ontology manager */
    OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
    
    /* Load input ontology */
    OWLOntology source = manager.loadOntologyFromOntologyDocument(inputFile);
    
    /* Save ontology in obo format into the output file */
    manager.saveOntology(source, new OBODocumentFormat(), IRI.create(outputFile));
  }
```
It worked for another ontologies like chebi, however, in this case it is throwing exceptions like the following :
```
SEVERE: MASKING ERROR «the axiom is not translated : EquivalentClasses(<http://purl.obolibrary.org/obo/OBI_0200175> ObjectUnionOf(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/OBI_0000299> <http://purl.obolibrary.org/obo/OBI_0000648>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/OBI_0000417> <http://purl.obolibrary.org/obo/OBI_0200178>)) )»
java.lang.Exception
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2172)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.error(OWLAPIOwl2Obo.java:2164)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:1588)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo$Translator.visit(OWLAPIOwl2Obo.java:2243)
	at org.semanticweb.owlapi.model.OWLEquivalentClassesAxiom.accept(OWLEquivalentClassesAxiom.java:105)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.lambda$accept$2(OWLAPIOwl2Obo.java:751)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.accept(OWLAPIOwl2Obo.java:751)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.lambda$tr$1(OWLAPIOwl2Obo.java:734)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:734)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:706)
	at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:51)
	at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:36)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:85)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1327)
	at de.li.basf.ontology.owl2obo.utils.Util.convertToObo(Util.java:34)
	at de.li.basf.ontology.owl2obo.Owl2Obo.main(Owl2Obo.java:37)
```
I think this is due to axioms that can not be converted into obo, which is normal. However, the application fails with this last exception:
```
Exception in thread "main" java.lang.IllegalStateException: labelMaker has not been set yet
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.lambda$getEntityLabel$25(FunctionalSyntaxObjectRenderer.java:685)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.getEntityLabel(FunctionalSyntaxObjectRenderer.java:685)
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.writeEntity2(FunctionalSyntaxObjectRenderer.java:658)
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.writeEntities(FunctionalSyntaxObjectRenderer.java:615)
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.writeSortedEntities(FunctionalSyntaxObjectRenderer.java:590)
	at org.semanticweb.owlapi.functional.renderer.FunctionalSyntaxObjectRenderer.renderAxioms(FunctionalSyntaxObjectRenderer.java:449)
	at org.obolibrary.obo2owl.OwlStringTools.translate(OwlStringTools.java:59)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.tr(OWLAPIOwl2Obo.java:736)
	at org.obolibrary.obo2owl.OWLAPIOwl2Obo.convert(OWLAPIOwl2Obo.java:706)
	at org.semanticweb.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:51)
	at org.semanticweb.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:36)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:85)
	at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1327)
	at de.li.basf.ontology.owl2obo.utils.Util.convertToObo(Util.java:34)
	at de.li.basf.ontology.owl2obo.Owl2Obo.main(Owl2Obo.java:37)
```
It comes from FunctionalSyntaxObjectRenderer class, which has not initialized its labelMarker property.

Is this a bug or am I missing something in my code?

Thanks for your time.

**Comment by ignazio1977** [comment]
It's a bug, the functional renderer is used to save untranslatable axioms and it should have been fully initialised, but the label extractor has not. You should be able to work around this dropping rdfs:label annotations from the untranslatable axioms.

**Comment by cmungall** [comment]
Hmm, robot converts it just fine, and robot uses the owlapi:

`robot convert -i /tmp/obi.owl -c false -o /tmp/obi.obo `

(the `-c false` is necessary to disable cardinality checks on text definition axioms)

But maybe because robot is not on owlapi v5 yet?

**Comment by ignazio1977** [comment]
It's a recent change to avoid livelock when using threadsafe ontology managers. We used to create a new ontology when saving untranslatable axioms, but that was bad - it attempted to upgrade a read lock to a write lock, unless two managers were available.

The fix was to amend the functional syntax serializer so that it'd accept an ontology or a collection of axioms, but that fix came with a bug.

**Comment by ignazio1977** [comment]
(Also, OWLAPI 4 uses a different approach, so it's not affected by this bug.)

**Comment by ignazio1977** [comment]
I fixed the problem in OWLAPI 5, but be advised that I get a different issue in both OWLAPI 4 and 5, looks more to do with the data:

>    multiple def tags not allowed. in frame:Frame(BFO:0000031 id( BFO:0000031)property_value( BFO:0000179 gdc xsd:string)property_value( IAO:0000112 The entries in your database are patterns instantiated as quality instances in your hard drive. The database itself is an aggregate of such patterns. When you create the database you create a particular instance of the generically dependent continuant type database. Each entry in the database is an instance of the generically dependent continuant type IAO: information content entity. xsd:string)name( generically dependent continuant)property_value( isDefinedBy http://purl.obolibrary.org/obo/bfo.owl)property_value( BFO:0000180 GenericallyDependentContinuant xsd:string)property_value( IAO:0000602 (iff (GenericallyDependentContinuant a) (and (Continuant a) (exists (b t) (genericallyDependsOnAt a b t)))) // axiom label in BFO2 CLIF: [074-001]  xsd:string{{http://purl.obolibrary.org/obo/IAO_0010000=http://purl.obolibrary.org/obo/bfo/axiom/074-001} {http://www.w3.org/1999/02/22-rdf-syntax-ns#type=owl:Axiom} })property_value( IAO:0000112 the sequence of this protein molecule; the sequence that is a copy thereof in that protein molecule. xsd:string)def( A continuant that is dependent on one or other independent continuant bearers. For every instance of A requires some instance of (an independent continuant type) B but which instance of B serves can change from time to time.)property_value( IAO:0000112 the pdf file on your laptop, the pdf file that is a copy thereof on my laptop xsd:string)def( b is a generically dependent continuant = Def. b is a continuant that g-depends_on one or more other entities. (axiom label in BFO2 Reference: [074-001]){{http://purl.obolibrary.org/obo/IAO_0010000=http://purl.obolibrary.org/obo/bfo/axiom/074-001} {http://www.w3.org/1999/02/22-rdf-syntax-ns#type=owl:Axiom} })is_a( BFO:0000002))

**Comment by fanavarro** [comment]
Thanks for your fix, @ignazio1977. What do you think about opening a new issue to discuss how to manage multiple definition declaration? I think this one is fixed so we can close it.

**Comment by ignazio1977** [comment]
I need to port the fix to version 6 before closing this, but feel free to open the new issue. I'm not clear on whether it's a bug or a problem in the data.

**Comment by ignazio1977** [comment]
The problem seems to be here: there are multiple values for `obo:IAO_0000115`. To me it looks like an attempt at editing the existing value that didn't remove the old value before adding the new one.

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/BFO_0000031">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000002"/>
        <obo:BFO_0000179>gdc</obo:BFO_0000179>
        <obo:BFO_0000180>GenericallyDependentContinuant</obo:BFO_0000180>
        <obo:IAO_0000112 xml:lang="en">The entries in your database are patterns instantiated as quality instances in your hard drive. The database itself is an aggregate of such patterns. When you create the database you create a particular instance of the generically dependent continuant type database. Each entry in the database is an instance of the generically dependent continuant type IAO: information content entity.</obo:IAO_0000112>
        <obo:IAO_0000112 xml:lang="en">the pdf file on your laptop, the pdf file that is a copy thereof on my laptop</obo:IAO_0000112>
        <obo:IAO_0000112 xml:lang="en">the sequence of this protein molecule; the sequence that is a copy thereof in that protein molecule.</obo:IAO_0000112>
        <obo:IAO_0000115 xml:lang="en">A continuant that is dependent on one or other independent continuant bearers. For every instance of A requires some instance of (an independent continuant type) B but which instance of B serves can change from time to time.</obo:IAO_0000115>
        <obo:IAO_0000115 xml:lang="en">b is a generically dependent continuant = Def. b is a continuant that g-depends_on one or more other entities. (axiom label in BFO2 Reference: [074-001])</obo:IAO_0000115>
        <obo:IAO_0000602>(iff (GenericallyDependentContinuant a) (and (Continuant a) (exists (b t) (genericallyDependsOnAt a b t)))) // axiom label in BFO2 CLIF: [074-001] </obo:IAO_0000602>
        <rdfs:isDefinedBy rdf:resource="http://purl.obolibrary.org/obo/bfo.owl"/>
        <rdfs:label xml:lang="en">generically dependent continuant</rdfs:label>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/BFO_0000031"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000115"/>
        <owl:annotatedTarget xml:lang="en">b is a generically dependent continuant = Def. b is a continuant that g-depends_on one or more other entities. (axiom label in BFO2 Reference: [074-001])</owl:annotatedTarget>
        <obo:IAO_0010000 rdf:resource="http://purl.obolibrary.org/obo/bfo/axiom/074-001"/>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/BFO_0000031"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000602"/>
        <owl:annotatedTarget>(iff (GenericallyDependentContinuant a) (and (Continuant a) (exists (b t) (genericallyDependsOnAt a b t)))) // axiom label in BFO2 CLIF: [074-001] </owl:annotatedTarget>
        <obo:IAO_0010000 rdf:resource="http://purl.obolibrary.org/obo/bfo/axiom/074-001"/>
    </owl:Axiom>

**Comment by fanavarro** [comment]
Hi @ignazio1977. Yes, the owl has two definitions for the same class while obo only allows one definition per term. In #861 we are discussing how to deal with classes with several labels, which are converted into names when translating to obo and, like this case, obo only allows one name per term.

**Comment by ignazio1977** [comment]
Adding different properties for extra labels or names would work on the obo to owl translation but it would still be a problem on the owl to obo - there is no way of figuring out which one of the values is the main one and which one is extra, so obo tools would need to be aware of the new properties. Hm.

**Comment by ignazio1977** [comment]
Anyway yes, the discussion on duplicate tags can be continued under #861
