### ISSUE TITLE
Trying to load a file fails.

### ISSUE THREAD

**Issue by bjonnh** [owlcs/owlapi#862]
Exception in thread "main" java.lang.NoSuchFieldError: UTF_32BE
	at org.semanticweb.owlapi.io.DocumentSources.wrap(DocumentSources.java:297)
	at org.semanticweb.owlapi.io.DocumentSources.wrapInputAsReader(DocumentSources.java:85)
	at org.semanticweb.owlapi.io.DocumentSources.wrapInputAsReader(DocumentSources.java:102)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:38)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:59)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:193)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1071)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1033)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:983)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1003)

I am using:
net.sourceforge.owlapi:owlapi-distribution:5.1.11

and just trying to load a file with: 
OWLManager.createOWLOntologyManager().loadOntologyFromOntologyDocument(file)

**Comment by ignazio1977** [comment]
The field that's missing has been in Apache Commons since version 2.2, and OWLAPI 5 has a dependency on Commons 2.4. I suspect your classpath has excluded that version in favor of a version that predates 2.2. Can you verify?

**Comment by bjonnh** [comment]
Yes the issue was with ELK and/or Hermit. I compiled the last version from git of ELK 0.5 (anyway hermit couldn't work with my ontology) and it seems to be working properly now.
