### ISSUE TITLE
Error when parsing expression

### ISSUE THREAD

**Issue by noorbakerally** [owlcs/owlapi#872]
I am getting an error when parsing the expression `<http://purl.oclc.org/NET/ssnx/ssn#Observation> or <http://www.irit.fr/recherches/MELODI/ontologies/SAN#Actuation>`. The codes and error are below. I have noticed that the error happens is from an imported ontology even if the class in the expression is in the ontology. I'm checking that they are in the ontology using `containsClassInSignature`

**Codes for parsing expression**
```
        ```
String exp = "<http://purl.oclc.org/NET/ssnx/ssn#Observation> or <http://www.irit.fr/recherches/MELODI/ontologies/SAN#Actuation>";
        parseManchesterExp(exp,ontology);
        public static OWLClassExpression parseManchesterExp(String exp, OWLOntology ontology){
        ManchesterOWLSyntaxEditorParser parser = new ManchesterOWLSyntaxEditorParser(
                ontology.getOWLOntologyManager().getOWLDataFactory(), exp);
        parser.setDefaultOntology(ontology);
        //System.out.println(exp);
        OWLClassExpression expC = null;

        try{
            expC = parser.parseClassExpression(exp);
        } catch (Exception e){
            e.printStackTrace();
        }

        return expC;
    }
```

```

**Error:**
org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered <http://www.irit.fr/recherches/MELODI/ontologies/SAN#Actuation> at line 1 column 52. Expected one of:
	Class name
	Object property name
	Data property name
	inverse
	not
	(
	{

	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl$ExceptionBuilder.build(ManchesterOWLSyntaxParserImpl.java:2757)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNonNaryClassExpression(ManchesterOWLSyntaxParserImpl.java:705)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseIntersection(ManchesterOWLSyntaxParserImpl.java:596)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseUnion(ManchesterOWLSyntaxParserImpl.java:618)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseClassExpression(ManchesterOWLSyntaxParserImpl.java:584)
	at org.semanticweb.owlapi.util.mansyntax.ManchesterOWLSyntaxParser.parseClassExpression(ManchesterOWLSyntaxParser.java:232)
	at ontology.OntologyUtils.parseManchesterExp(OntologyUtils.java:441)
	at examples.DogontFull.main(DogontFull.java:72)

**Comment by ignazio1977** [comment]
It works for me. I suspect your ontology does not have the entities you're using. Check their namespaces.

        OWLOntology ontology = OWLManager.createOWLOntologyManager().createOntology();
        String exp =
            "<http://purl.oclc.org/NET/ssnx/ssn#Observation> or <http://www.irit.fr/recherches/MELODI/ontologies/SAN#Actuation>";
        OWLDataFactory df = OWLManager.getOWLDataFactory();
        ontology.add(df.getOWLDeclarationAxiom(
            df.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Observation"))));
        ontology.add(df.getOWLDeclarationAxiom(df.getOWLClass(
            IRI.create("http://www.irit.fr/recherches/MELODI/ontologies/SAN#Actuation"))));

        ManchesterOWLSyntaxEditorParser parser = new ManchesterOWLSyntaxEditorParser(
            ontology.getOWLOntologyManager().getOWLDataFactory(), exp);
        parser.setDefaultOntology(ontology);
        // System.out.println(exp);
        OWLClassExpression expC = parser.parseClassExpression(exp);
        System.out.println("check.main() " + expC);

**Comment by noorbakerally** [comment]
This is the ontology i am using: http://homepages.laas.fr/nseydoux/ontologies/IoT-O.owl.
I forgot to precise the parse did work in cases where the entities in the expression are not from an imported ontology. I have noticed that this error raises when the entities are from an imported ontology.
For example, in the codes below, before parsing the expression, I do a check if the class is in the ontology and then i parse the expression. As you can see, the class are well in the ontology and yet the expression cannot be parsed.

     ```
System.out.println("Check if class exist");
        System.out.println("======================");
        iri = "http://purl.oclc.org/NET/ssnx/ssn#Observation";
        boolean result = dogont.getOWLOntology().containsClassInSignature(IRI.create(iri));
        System.out.println("Contains class "+iri+" :"+result);

        iri = "http://www.irit.fr/recherches/MELODI/ontologies/SAN#Actuation";
        result = dogont.getOWLOntology().containsClassInSignature(IRI.create(iri));
        System.out.println("Contains class "+iri+" :"+result);


```
        OntologyUtils.parseManchesterExp(exp,dogont.getOWLOntology());



```

Check if class exist
======================
Contains class http://purl.oclc.org/NET/ssnx/ssn#Observation :true
Contains class http://www.irit.fr/recherches/MELODI/ontologies/SAN#Actuation :true
org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered <http://www.irit.fr/recherches/MELODI/ontologies/SAN#Actuation> at line 1 column 52. Expected one of:
	Class name
	Object property name
	Data property name
	inverse
	not
	(
	{

	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl$ExceptionBuilder.build(ManchesterOWLSyntaxParserImpl.java:2757)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseNonNaryClassExpression(ManchesterOWLSyntaxParserImpl.java:705)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseIntersection(ManchesterOWLSyntaxParserImpl.java:596)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseUnion(ManchesterOWLSyntaxParserImpl.java:618)
	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl.parseClassExpression(ManchesterOWLSyntaxParserImpl.java:584)
	at org.semanticweb.owlapi.util.mansyntax.ManchesterOWLSyntaxParser.parseClassExpression(ManchesterOWLSyntaxParser.java:232)
	at ontology.OntologyUtils.parseManchesterExp(OntologyUtils.java:443)
	at examples.DogontFull.main(DogontFull.java:88)
```

**Comment by noorbakerally** [comment]
@ignazio1977, were you able to reproduce the error with the above ontology ?
thanks

**Comment by ignazio1977** [comment]
There is no method to navigate the imports closure to get the result you wish, but you can work around the problem this way:

Replace

    parser.setDefaultOntology(ontology);

with

    ontology.getImportsClosure().forEach(parser::setDefaultOntology);
    parser.setDefaultOntology(ontology);

Tis will add all the declared entities to the parser structures and then still set the default ontology yo the value you need. Parsing should then work.

**Comment by ignazio1977** [comment]
Alternatively, look at the code for DLQueryExample, which sets up short form providers instead.
