### ISSUE TITLE
SAXException from AutoIRIMapper at debug logging level

### ISSUE THREAD

**Issue by jvendetti** [owlcs/owlapi#878]
I'm attempting to upgrade our [BioPortal](https://bioportal.bioontology.org/) ontology repository software from OWL API version 4.3.2 to 4.5.13. After upgrading to this newer version, loading several of the ontologies in the repository result in a SAXException from the AutoIRIMapper (one such ontology is attached). The following code snippet reproduces the exception:

```
OWLOntologyLoaderConfiguration conf = new OWLOntologyLoaderConfiguration();
conf = conf.setMissingImportHandlingStrategy(MissingImportHandlingStrategy.SILENT);

File file = new File("src/test/resources/cno/cnov0_5.owl");
File rootDir = new File("src/test/resources/cno");
AutoIRIMapper mapper = new AutoIRIMapper(rootDir, true);

OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
manager.getIRIMappers().add(mapper);
FileDocumentSource fileDocumentSource = new FileDocumentSource(file);
OWLOntology ontology = manager.loadOntologyFromOntologyDocument(fileDocumentSource, conf);
```

[cnov0_5.owl.zip](https://github.com/owlcs/owlapi/files/3561456/cnov0_5.owl.zip)

The ontology object is viable despite the exception. It's unclear to me if the exception is benign, or if there's something wrong with the way we're using the mapper. To follow is the full stack trace:

```
13:12:07 [main] DEBUG o.s.owlapi.util.AutoIRIMapper - Exception reading file
org.xml.sax.SAXException: null
	at org.semanticweb.owlapi.util.AutoIRIMapper.startElement(AutoIRIMapper.java:341)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
	at org.semanticweb.owlapi.util.AutoIRIMapper.parseFile(AutoIRIMapper.java:293)
	at org.semanticweb.owlapi.util.AutoIRIMapper.parseIfExtensionSupported(AutoIRIMapper.java:254)
	at org.semanticweb.owlapi.util.AutoIRIMapper.processFile(AutoIRIMapper.java:223)
	at org.semanticweb.owlapi.util.AutoIRIMapper.mapFiles(AutoIRIMapper.java:206)
	at org.semanticweb.owlapi.util.AutoIRIMapper.getDocumentIRI(AutoIRIMapper.java:187)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.getDocumentIRIFromMappers(OWLOntologyManagerImpl.java:1681)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1117)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadImports(OWLOntologyManagerImpl.java:1864)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1902)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1651)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:278)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1558)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:370)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:236)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:658)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:201)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.parse(RDFParser.java:145)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:73)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:221)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1293)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1233)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1190)
```

**Comment by ignazio1977** [comment]
Loading the file via `FileDocumentSource` means the mapper is not used for this file, only for any other imported ontologies - which would then be downloaded from the web, if available (no failure if they're not available because of the config settings). So the ontology itself is ok, but its imports closure might not be.

The file looks correct, but is it the only file in the folder? I'm wondering if the error is coming from trying to parse the ontology entry for another file, given that the stack trace does not provide that information (the code should be changed to do that, incidentally).

**Comment by ignazio1977** [comment]
I had a look in the code and the exception is harmless. It is thrown to stop the parsing early, bit of a clunky optimization due to not having a better way to avoid parsing the whole file once the ontology header has been found.

The exceptions used to just be ignored; we changed that to log at debug level, for when an exception is actually useful because of bad input; however, there it should ignore the expected exceptions - it just creates misleading logs.

**Comment by jvendetti** [comment]
Apologies for this late reply @ignazio1977. That was the only file in the folder - I see now that having the AutoIRIMapper code in the snippet wasn't necessary. Thanks for the help / explanation of the exception. Very much appreciated!
