### ISSUE TITLE
Null exception in HermiT for pizza ontology

### ISSUE THREAD

**Issue by rlbns** [owlcs/owlapi#900]
When using owl-api and HermiT on the pizza ontology, a null pointer exception occurs when the reasoner is asked for super classes. Here is the call stack:

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at org.semanticweb.HermiT.Reasoner.getTableau(Reasoner.java:2023)
	at org.semanticweb.HermiT.Reasoner.isConsistent(Reasoner.java:709)
	at org.semanticweb.HermiT.Reasoner.throwInconsistentOntologyExceptionIfNecessary(Reasoner.java:2295)
	at org.semanticweb.HermiT.Reasoner.checkPreConditions(Reasoner.java:2288)
	at org.semanticweb.HermiT.Reasoner.getHierarchyNode(Reasoner.java:953)
	at org.semanticweb.HermiT.Reasoner.getSuperClasses(Reasoner.java:839)

I'm using version 1.4.3.517 of HermiT with version 5.1.7 of owl-api.

I'm using this version of the pizza ontology:
https://github.com/owlcs/pizza-ontology/blob/master/pizza.owl

Asking for sub classes does not cause the same problem.

**Comment by rlbns** [comment]
getSuperClasses() was being called after reasoner.dispose() - this is not an error.
