### ISSUE TITLE
OWLOntologyAlreadyExistsException when calling to saveOntology

### ISSUE THREAD

**Issue by lewismc** [owlcs/owlapi#915]
I initially create and populate an Ontology with Jena and save it to disk. I then want to open it and save it again using the OWLAPI. My code looks as follows
```
        val outFile = new FileWriter(file)
        RDFDataMgr.write(outFile, model, org.apache.jena.riot.RDFFormat.TURTLE_PRETTY)
        outFile.close()

        val owlManager = OWLManager.createOWLOntologyManager
        val ont = owlManager.loadOntologyFromOntologyDocument(file)
        owlManager.saveOntology(ont, new formats.TurtleDocumentFormat())
```
This results in the following
```
[error] (run-main-4) org.semanticweb.owlapi.model.OWLOntologyAlreadyExistsException: Ontology already exists. OntologyID(OntologyIRI(<http://sweetontology.net/human>) VersionIRI(<null>))
[error] org.semanticweb.owlapi.model.OWLOntologyAlreadyExistsException: Ontology already exists. OntologyID(OntologyIRI(<http://sweetontology.net/human>) VersionIRI(<null>))
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1122)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1020)
[error] 	at sweet.tools.augment_wikidata_definitions$.$anonfun$main$4(augment_wikidata_definitions.scala:60)
[error] 	at sweet.tools.augment_wikidata_definitions$.$anonfun$main$4$adapted(augment_wikidata_definitions.scala:34)
[error] 	at scala.Option.foreach(Option.scala:437)
[error] 	at sweet.tools.augment_wikidata_definitions$.$anonfun$main$3(augment_wikidata_definitions.scala:34)
[error] 	at sweet.tools.augment_wikidata_definitions$.$anonfun$main$3$adapted(augment_wikidata_definitions.scala:32)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at sweet.tools.augment_wikidata_definitions$.main(augment_wikidata_definitions.scala:32)
[error] 	at sweet.tools.augment_wikidata_definitions$.main(augment_wikidata_definitions.scala:17)
[error] 	at sweet.tools.augment_wikidata_definitions.main(augment_wikidata_definitions.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: org.semanticweb.owlapi.model.OWLOntologyRenameException: Could not rename ontology. An ontology with this ID already exists: OntologyID(OntologyIRI(<http://sweetontology.net/human>) VersionIRI(<null>))
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.checkForOntologyIDChange(OWLOntologyManagerImpl.java:744)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.enactChangeApplication(OWLOntologyManagerImpl.java:597)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actuallyApply(OWLOntologyManagerImpl.java:645)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChangesAndGetDetails(OWLOntologyManagerImpl.java:614)
[error] 	at org.semanticweb.owlapi.model.HasApplyChanges.applyChanges(HasApplyChanges.java:43)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.applyChange(OWLOntologyManagerImpl.java:693)
[error] 	at org.semanticweb.owlapi.model.OWLOntology.applyChange(OWLOntology.java:92)
[error] 	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.lambda$applyChange$174(ConcurrentOWLOntologyImpl.java:1516)
[error] 	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.withWriteLock(ConcurrentOWLOntologyImpl.java:161)
[error] 	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.applyChange(ConcurrentOWLOntologyImpl.java:1516)
[error] 	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.chooseAndSetOntologyIRI(OWLRDFConsumer.java:1509)
[error] 	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.endModel(OWLRDFConsumer.java:1420)
[error] 	at org.semanticweb.owlapi.rio.RioOWLRDFConsumerAdapter.endRDF(RioOWLRDFConsumerAdapter.java:80)
[error] 	at org.semanticweb.owlapi.rio.RioParserImpl$RioParserRDFHandler.endRDF(RioParserImpl.java:281)
[error] 	at org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:209)
[error] 	at org.semanticweb.owlapi.rio.RioParserImpl.parseDocumentSource(RioParserImpl.java:174)
[error] 	at org.semanticweb.owlapi.rio.RioParserImpl.parse(RioParserImpl.java:127)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:194)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1107)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)
[error] 	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1020)
[error] 	at sweet.tools.augment_wikidata_definitions$.$anonfun$main$4(augment_wikidata_definitions.scala:60)
[error] 	at sweet.tools.augment_wikidata_definitions$.$anonfun$main$4$adapted(augment_wikidata_definitions.scala:34)
[error] 	at scala.Option.foreach(Option.scala:437)
[error] 	at sweet.tools.augment_wikidata_definitions$.$anonfun$main$3(augment_wikidata_definitions.scala:34)
[error] 	at sweet.tools.augment_wikidata_definitions$.$anonfun$main$3$adapted(augment_wikidata_definitions.scala:32)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at sweet.tools.augment_wikidata_definitions$.main(augment_wikidata_definitions.scala:32)
[error] 	at sweet.tools.augment_wikidata_definitions$.main(augment_wikidata_definitions.scala:17)
[error] 	at sweet.tools.augment_wikidata_definitions.main(augment_wikidata_definitions.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
```
I've looked at powerpoint presentations from @ignazio1977 demonstrating how this is done and I've tried creating a new `OWLOntologyManager` and executing `.removeOntology(ont);` but it still results in the same...
 
How do I open a file, and then successfully write that file back to disk?

Some may ask why I would want to do this... we are starting to work with Jena on all of our projects but like the way Turtle is formatted when written by the OWLAPI.

Thanks in advance for any assistance.

**Comment by ignazio1977** [comment]
The issue is related to imported ontologies - looks like your ontology might have the same iri as an imported ontology. Can you share its contents?

**Comment by lewismc** [comment]
Thanks for quick response @ignazio1977 

> Can you share its contents?

Yes, https://github.com/ESIPFed/sweet/blob/master/src/human.ttl

**Comment by ignazio1977** [comment]
It's a known issue to do with cyclic imports. you import `repr` which imports `relamath` and `reprmath`, `relamath` imports `repr`. The problem is that entities are not declared everywhere, and when parsing the recursive imports OWLAPI does not parse the declarations before attempting to parse the rest of the files; this ends up causing the same ontology to look like two different ontologies with the same IRI, because the first parse could not use the declarations that were available on the second parse (there are two parse steps because of the cycle in imports), and so when checking if we just parsed the same ontology twice (which would be fine) we get an unexpected result, because it looks like the axioms in the ontologies are not the same.

There isn't a good fix for this yet, partly because the issue is format dependent; some of the OWLAPI parsers cannot easily be modified to properly handle import cycles.

In the past, changing the first ontology included from a cycle has helped. Try importing `reprMath` rather than `repr` (or `relaMath`). A different starting point sometimes means that the declarations are found in a non ambiguous manner, and then the problem does not happen.

**Comment by lewismc** [comment]
Thanks @ignazio1977 I really appreciate you taking the time to explain that.

> Try importing reprMath rather than repr (or relaMath). A different starting point sometimes means that the declarations are found in a non ambiguous manner, and then the problem does not happen.

I can't really do this as I am recursing through every file in this ontology suite... it looks like I'll just need to work with Jena for the time being. Thank you
