### ISSUE TITLE
ClassNotFoundException: OWLXMLWriter

### ISSUE THREAD

**Issue by RitaRandazzo01** [owlcs/owlapi#917]
Hey there,
I'm trying to get Konclude reasoner in OWLAPI5, so I download this fork [https://github.com/ignazio1977/owllink-owlapi/](https://github.com/ignazio1977/owllink-owlapi/) and I add it as a Jar into my project, after adding all dependencies. Despite this, it currently produces the following null pointer exception:

 `Exception in thread "main" java.lang.NoClassDefFoundError: org/coode/owlapi/owlxml/renderer/OWLXMLWriter
	at org.semanticweb.owlapi.owllink.renderer.OWLlinkXMLRenderer.render(OWLlinkXMLRenderer.java:67)
	at org.semanticweb.owlapi.owllink.HTTPSessionImpl.performRequests(HTTPSessionImpl.java:141)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.performRequests(OWLlinkHTTPXMLReasoner.java:457)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.performRequest(OWLlinkHTTPXMLReasoner.java:461)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.createDefaultKB(OWLlinkHTTPXMLReasoner.java:445)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.<init>(OWLlinkHTTPXMLReasoner.java:64)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasonerFactory.createNonBufferingReasoner(OWLlinkHTTPXMLReasonerFactory.java:52)
	at KoncludeTest.main(KoncludeTest.java:34)
Caused by: java.lang.ClassNotFoundException: org.coode.owlapi.owlxml.renderer.OWLXMLWriter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more`

How can I solve this exception? 
Best, Rita

**Comment by ignazio1977** [comment]
Can you share the setup of your project? Looks like the owlapi-parsers.jar is not in the classpath.

**Comment by RitaRandazzo01** [comment]
Yes, owlapi-parsers.jar  was missing! Thank you for your help. 
Rita
