### ISSUE TITLE
java.lang.NullPointerException on import

### ISSUE THREAD

**Issue by mikael1234** [owlcs/owlapi#921]
Discussion from HermiT forum: https://groups.google.com/forum/#!topic/hermit-users/pFJ0YUuePpM

Command

 java -jar HermiT.jar  -cO -v2 file:///tmp/socrates.maowl

results error

Processing file:///tmp/socrates.maowl
1 actions
Exception in thread "main" java.lang.NullPointerException
        at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.parseOntology(ManchesterOWLSyntaxEditorParser.java:2607)
        at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxOntologyParser.parse(ManchesterOWLSyntaxOntologyParser.java:125)
        at uk.ac.manchester.cs.owl.owlapi.ParsableOWLOntologyFactory.loadOWLOntology(ParsableOWLOntologyFactory.java:206)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:880)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:800)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:758)
        at org.semanticweb.HermiT.cli.CommandLine.main(Unknown Source)

Attached socrates.maowl and imported file socrates_abox.maowl.

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

[socrates.maowl.txt](https://github.com/owlcs/owlapi/files/4421187/socrates.maowl.txt)
[socrates_abox.maowl.txt](https://github.com/owlcs/owlapi/files/4421188/socrates_abox.maowl.txt)

**Comment by mikael1234** [comment]
[socrates.maowl.txt](https://github.com/owlcs/owlapi/files/4421169/socrates.maowl.txt)
[socrates_abox.maowl.txt](https://github.com/owlcs/owlapi/files/4421170/socrates_abox.maowl.txt)

**Comment by ignazio1977** [comment]
Can you specify the HermiT version you're using? We need to check which OWLAPI version it includes.

**Comment by ignazio1977** [comment]
Problem and solutions discussed https://github.com/owlcs/hermit-reasoner/issues/8
