### ISSUE TITLE
v5.1.15: "operands cannot be null or empty" while parsing document

### ISSUE THREAD

**Issue by sszuev** [owlcs/owlapi#951]
Consider the following ontology:

```
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .

<http://i>  a   owl:NamedIndividual ;
        a       [ a            owl:Class ;
                  owl:unionOf  ()
                ] .

[ a       owl:Ontology ] .
```
Or
```
Declaration(NamedIndividual(<http://i>))
ClassAssertion(ObjectUnionOf() <http://i>)
```

The exception:

```
Exception in thread "main" java.lang.NullPointerException: operands cannot be null or empty
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.checkValidForNAryExpressions(OWLAPIPreconditions.java:120)
	at uk.ac.manchester.cs.owl.owlapi.OWLNaryBooleanClassExpressionImpl.<init>(OWLNaryBooleanClassExpressionImpl.java:39)
	at uk.ac.manchester.cs.owl.owlapi.OWLObjectUnionOfImpl.<init>(OWLObjectUnionOfImpl.java:35)
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLObjectUnionOf(OWLDataFactoryImpl.java:651)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.Translators$ObjectUnionOfTranslator.translate(Translators.java:1641)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.Translators$ObjectUnionOfTranslator.translate(Translators.java:1619)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.Translators$TranslatorAccessor.translateClassExpressionInternal(Translators.java:270)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.Translators$TranslatorAccessor.translateClassExpression(Translators.java:321)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handle(TripleHandlers.java:422)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TypeAxiomHandler.handleTriple(TripleHandlers.java:2375)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.applyAnns(TripleHandlers.java:327)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.lambda$null$32(OWLRDFConsumer.java:2310)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.lambda$null$33(OWLRDFConsumer.java:2310)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.lambda$iterateResources$34(OWLRDFConsumer.java:2309)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.iterateResources(OWLRDFConsumer.java:2308)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.consumeAnnotatedAxioms(TripleHandlers.java:337)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.mopUp(TripleHandlers.java:476)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.endModel(OWLRDFConsumer.java:1408)
	at org.semanticweb.owlapi.rdf.turtle.parser.OWLRDFConsumerAdapter.handleEnd(OWLRDFConsumerAdapter.java:73)
	at org.semanticweb.owlapi.rdf.turtle.parser.TurtleParser.parseDocument(TurtleParser.java:187)
	at org.semanticweb.owlapi.rdf.turtle.parser.TurtleOntologyParser.parse(TurtleOntologyParser.java:54)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:194)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.load(OWLOntologyManagerImpl.java:1107)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1057)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntologyFromOntologyDocument(OWLOntologyManagerImpl.java:1007)
```

notes: 
- the ontology above is not fully valid, but such ontology can be created by different tools and APIs, including Protege and OWL-API itself (v <=5.1.14) 
- more test-cases that could help detect regressions can be found in ONT-API codebase

**Comment by ignazio1977** [comment]
Yes, allowing empty constructs for unions and intersections is an ancient bug that should have been fixed a long time ago. It contravenes the specs in an obvious way. The document requires two or more distinct arguments, so even one argument should have been rejected (same with duplicate arguments where duplicates should be dropped - a topic that raised long discussions a few years back).

**Comment by sszuev** [comment]
OWLAPIs v <= 5.1.14 do not allow duplicates on factory level for manually added things (at least some methods). 
This is, off course, right behavior. 
But, in my opinion, disabling loading existing ontology documents is a major regression. 
They must be allowed. Any RDF must be allowed.
One use case - is to fix them using the OWLAPI, and, obviously, if you can't load then you can't fix.
I think the purpose of API is to provide correct grammar, not to fix on fly particular errors in the words.
So I don't think this can be called as ancient bug, I rather think, this is well known behavior which can be problem only to newbies.

**Comment by sszuev** [comment]
I think any RDF-document must be loadable and violation of this rule in some release is a major issue, a regression. 
Also I think the core API must be responsible for grammar, not for mistakes in words or sentences.

**Comment by ykazakov** [comment]
I just noticed this new behaviour regarding the empty list of operands. Should it be then applied consistently? Looks like the empty `ObjectOneOf` is still permitted:

```
OWLManager.getOWLDataFactory().getOWLObjectOneOf(); // <- OK??
OWLManager.getOWLDataFactory().getOWLSameIndividualAxiom(); // <- Not OK
```

Is it an oversight?

**Comment by ignazio1977** [comment]
Most likely my mistake, yes. I haven't checked the specs for oneOf, I imagine no arguments could possibly only mean bottom, if the language even allows it.

**Comment by ykazakov** [comment]
According to [OWL2 Grammar](https://www.w3.org/TR/owl2-syntax/#Appendix:_Complete_Grammar_.28Normative.29) no construct can have empty operands. Only HasKey may contain an empty pair of `()` (not directly as operands).

**Comment by nandikajain** [comment]
@ignazio1977 Can I take up this issue?

**Comment by ignazio1977** [comment]
@nandikajain of course
