### ISSUE TITLE
EntitySearcher.getSuperProperties fails when parent is inverse

### ISSUE THREAD

**Issue by henrietteharmse** [owlcs/owlapi#964]
Here is an example ontology:
```
<?xml version="1.0"?>
<rdf:RDF xmlns="http://henrietteharmse.com/tutorial/owlapi/"
     xml:base="http://henrietteharmse.com/tutorial/owlapi/"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://henrietteharmse.com/tutorial/owlapi/"/>     
    <owl:ObjectProperty rdf:about="http://henrietteharmse.com/tutorial/owlapi/capable_of"/>
    <owl:ObjectProperty rdf:about="http://henrietteharmse.com/tutorial/owlapi/enabled_by">
        <rdfs:subPropertyOf>
            <rdf:Description>
                <owl:inverseOf rdf:resource="http://henrietteharmse.com/tutorial/owlapi/capable_of"/>
            </rdf:Description>
        </rdfs:subPropertyOf>
    </owl:ObjectProperty>
</rdf:RDF>
```

Here is the code to reproduce the error:
```
import org.semanticweb.owlapi.model.*;
import org.semanticweb.owlapi.search.EntitySearcher;

public class InversePropertyProblem {
    public static void main(String[] args){
        try {
            OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
            IRI ontologyIRIToLoad = IRI.create(args[0]);
            OWLOntology ontology = manager.loadOntologyFromOntologyDocument(ontologyIRIToLoad);
            OWLDataFactory owlDataFactory = manager.getOWLDataFactory();
            IRI objectPropertyIRI = IRI.create("http://henrietteharmse.com/tutorial/owlapi/enabled_by");
//            IRI objectPropertyIRI = IRI.create("http://purl.obolibrary.org/obo/RO_0002333");
            OWLObjectProperty objectProperty = owlDataFactory.getOWLObjectProperty(objectPropertyIRI);
            EntitySearcher.getSuperProperties(objectProperty, ontology.importsClosure())
                    .forEach(superObjectPropertyExpression -> {
                        System.out.println(superObjectPropertyExpression.toString());
                    });
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
}
```

It throws the following exception:
```
java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLObjectInverseOfImpl cannot be cast to org.semanticweb.owlapi.model.OWLObjectProperty
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2746)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.owlapi.tutorial.InversePropertyProblem.main(InversePropertyProblem.java:18)
```

The actual ontology where this happens is: `http://purl.obolibrary.org/obo/to.owl`
The object property having this issue is: `http://purl.obolibrary.org/obo/RO_0002333`

We are using the owlapi to index about over 250 biomedical ontologies. For 1 of the ontologies we ran into this problem. Is there a better way to deal with this?

**Comment by ignazio1977** [comment]
The issue stems from the declaration of EntitySearcher.getSuperProperties(), where the type of the first argument determines the type of the elements in the response stream, then used to infer the types of the lambda as argument to forEach.

It's a bug, because of the situation your code shows - it shouldn't be possible for the returned elements to not match that type. While I figure out how to sort the signature, a workaround is to cast the first argument to a type compatible with all results:

EntitySearcher.getSuperProperties((OWLObjectPropertyExpression)objectProperty, ontology.importsClosure())
                    .forEach(superObjectPropertyExpression -> {
                        System.out.println(superObjectPropertyExpression.toString());
                    });

This forces the return type to be a Stream<OWLObjectPropertyExpression> that covers both simple object properties and inverse object properties.
Alternatively, if in your indexing code you don't use anonymous properties (i.e., inverses), you could filter those out of the returned stream before applying your lambda.
