### ISSUE TITLE
Unable to save ontology in NTriples

### ISSUE THREAD

**Issue by dns-148** [owlcs/owlapi#999]
I can't save my ontology in NTriples or any RDF Format, but it's successfully save when using OWL Format.

The format that already tried and give error:
```
NTriplesDocumentFormat nTriplesFormat = new NTriplesDocumentFormat();
N3DocumentFormat n3Format = new N3DocumentFormat();
TrigDocumentFormat trigFormat = new TrigDocumentFormat();
TurtleDocumentFormat  turtleFormat = new TurtleDocumentFormat();
RioTurtleDocumentFormat  rioFormat = new RioTurtleDocumentFormat();
```

The ontology:

```
SameIndividual(<http://www.example.com/individual/eq#PB> )
SameIndividual(<http://www.example.com/individual/eq#transY> )
SameIndividual(<http://www.example.com/individual/eq#symX> )
SameIndividual(<http://www.example.com/individual/eq#OC> )
SameIndividual(<http://www.example.com/individual/eq#transZ> )
SameIndividual(<http://www.example.com/individual/eq#SAA> )
SameIndividual(<http://www.example.com/individual/eq#transX> )
SameIndividual(<http://www.example.com/individual/eq#OAC> )
SameIndividual(<http://www.example.com/individual/eq#refO> )
SameIndividual(<http://www.example.com/individual/eq#refS> )
SameIndividual(<http://www.example.com/individual/eq#SA> )
SameIndividual(<http://www.example.com/individual/eq#PAB> )
SameIndividual(<http://www.example.com/individual/eq#transX> <http://www.example.com/individual/eq#transY> <http://www.example.com/individual/eq#transZ> )
SameIndividual(<http://www.example.com/individual/eq#symY> )
```

The code to produce the ontology (I tried to do inference based on rule OWL 2 RL The Semantics of Equality ([OWL 2 Web Ontology Language
Profiles](https://www.w3.org/TR/owl2-profiles/#Reasoning_in_OWL_2_RL_and_RDF_Graphs_using_Rules)) ):

```
    public class InferredSameIndividualAxiomGenerator extends InferredIndividualAxiomGenerator<OWLSameIndividualAxiom>{
    @Override
    protected void addAxioms(OWLNamedIndividual entity, 
                OWLReasoner reasoner, 
                OWLDataFactory dataFactory, 
                Set<OWLSameIndividualAxiom> result) {

        Set<OWLNamedIndividual> sameIndividuals = asUnorderedSet(reasoner.getSameIndividuals(entity).entities());
        sameIndividuals.add(entity);
        result.add(dataFactory.getOWLSameIndividualAxiom(entity, entity));
        if (sameIndividuals.size() > 1) 
            result.add(dataFactory.getOWLSameIndividualAxiom(sameIndividuals));
    }

    @Override
    public String getLabel() {
        return "Same Individuals T(?x, owl:sameAs, ?y)";
    }
}
```
The error message that produced, when saving file with `ontologyManager.saveOntology(ontologyInferred, nTriplesFormat, IRI.create(file.toURI()));`:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
    at java.base/java.util.Objects.checkIndex(Objects.java:373)
    at java.base/java.util.ArrayList.get(ArrayList.java:426)
    at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1321)
    at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1321)
    at org.semanticweb.owlapi.rdf.model.AbstractTranslator.lambda$visit$3(AbstractTranslator.java:710)
    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
    at org.semanticweb.owlapi.rdf.model.AbstractTranslator.visit(AbstractTranslator.java:709)
    at org.semanticweb.owlapi.model.OWLSameIndividualAxiom.accept(OWLSameIndividualAxiom.java:51)
    at org.semanticweb.owlapi.rdf.model.AbstractTranslator.translate(AbstractTranslator.java:288)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
    at org.semanticweb.owlapi.rdf.RDFRendererBase.createGraph(RDFRendererBase.java:484)
    at org.semanticweb.owlapi.rdf.RDFRendererBase.createGraph(RDFRendererBase.java:471)
    at org.semanticweb.owlapi.rdf.RDFRendererBase.lambda$renderEntities$5(RDFRendererBase.java:294)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
    at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1002)
    at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
    at org.semanticweb.owlapi.rdf.RDFRendererBase.renderEntities(RDFRendererBase.java:295)
    at org.semanticweb.owlapi.rdf.RDFRendererBase.renderInOntologySignatureEntities(RDFRendererBase.java:280)
    at org.semanticweb.owlapi.rdf.RDFRendererBase.renderOntologyComponents(RDFRendererBase.java:263)
    at org.semanticweb.owlapi.rdf.RDFRendererBase.render(RDFRendererBase.java:258)
    at org.semanticweb.owlapi.rio.RioStorer.storeOntology(RioStorer.java:230)
    at org.semanticweb.owlapi.util.AbstractOWLStorer.store(AbstractOWLStorer.java:85)
    at org.semanticweb.owlapi.util.AbstractOWLStorer.storeOntology(AbstractOWLStorer.java:72)
    at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1324)
    at preprocess.PositiveInference.inferringSemanticsofEquality(PositiveInference.java:117)
    at preprocess.PositiveInference.inferencing(PositiveInference.java:85)
    at preprocess.PositiveInference.main(PositiveInference.java:65)
```

From: [stackoverflow](https://stackoverflow.com/questions/67697302/cant-save-the-ontology-with-ntriples-owlapi)

**Comment by ignazio1977** [comment]
The issue is here:

`result.add(dataFactory.getOWLSameIndividualAxiom(entity, entity));`

https://www.w3.org/TR/owl2-profiles/#Reasoning_in_OWL_2_RL_and_RDF_Graphs_using_Rules says that an individual is owl:sameAs itself, but these cannot be represented as OWL axioms.

https://www.w3.org/TR/owl2-syntax/#Individual_Equality shows that the individuals must be two or more *distinct* individuals. The OWL/XML format doesn't disallow sameAs axioms with only one individual, but the other formats do.

There's no doubt that an individual is the same individual as itself, so semantically the inference is valid, if trivial. But the axiom cannot be included in a syntactically valid OWL 2 ontology.

Similarly, equivalent classes, disjoint classes, properties and so on, must have more than one argument.
the same kind of restriction was recently discussed on this issue tracker about syntactic restrictions on non simple properties - some inferences cannot be materialised because they violate syntactic restrictions.
